- _data/sponsors.yml
- _includes/_sponsors.html
- assets/main.scss
Adds a general two-column-list I've used before (e.g. Bitcoin.org) and then customizes it to this particular application.  Also puts Pfeffer's quote in quotations for reasons described in the YAML file (feel free to drop that commit if you disagree).
Note the unused `br.clear` entry in the CSS can be useful if a list with an odd number of entries is interacting with other floating content.  That's not the case now, so it's not used, but it's implemented against that future situation.
I would suggest adding some content for Casares, as his entry looks lonely without it.
> Use a two-column list for sponsors (when screen space is wide enough)

- _data/sponsors.yml
- _includes/sponsors.html
- index.md
This adds our sponsors to the home page.
> Add sponsors to index page

- _data/associates.yml
- _includes/associates.html
- _layouts/page.html
- about.md
- assets/css/main.scss
closes #11 
Adds motivation quotes. I don't think this looks very good at the moment. Perhaps we should use the two column layout from #9.
Also need to add thumbnails and quotes from @harding and @marcinja (assuming you guys want that?)
> Add motivation quotes

- _data/associates.yml
- _includes/associates.html
- _includes/sponsors.html
- assets/css/main.scss
> Founding sponsors on one row

- _includes/newsletter-signup.html
- _layouts/newsletter.html
- _posts/en/newsletters/2018-06-08-newsletter.md
- _posts/en/newsletters/2018-06-26-newsletter.md
- _posts/en/newsletters/2018-07-03-newsletter.md
- _posts/en/newsletters/2018-07-10-newsletter.md
- index.md
- newsletters.md
Note that this is based on #18 which should be tested and merged first.
> Add email subscription form to / and /newsletters

- _posts/en/newsletters/2018-07-17-newsletter.md
Based on top of #19 .  As before, feel free to push/amend/rebase commits on my branch.
One note: a possible dashboard item I ended up removing from this newsletter is that my node has observered a 7x increase in the number of below-default-min-feerate transactions in its mempool over the most I've ever seen before.  My guess is that this is just the result of enough more people changing that default setting so that we're forming a better relay network for sub-default txes and they're propagating better.  There's really nothing for businesses to do about that, I think, so I decided that it was just a bunch of irrelevant information.  However, I could write it back up again if you think it'd be interesting.
One question for @jnewbery: do you use the Markdown at all in generating the emailed …
> Add newsletter #4 (2018-07-17)

- _includes/sponsors.html
- assets/css/main.scss
On Firefox, I was having the issues mentioned in https://github.com/bitcoinops/bitcoinops.github.io/pull/30#issuecomment-406467996 despite the fix introduced in #31, so here's a solution that works for me (tested in FF and Chromium with various screen widths).
> Always start a new row of content for <h2>s

- .travis.yml
- _posts/en/2018-07-20-announcing-bitcoin-optech.md
- _posts/en/newsletters/2018-07-17-newsletter.md
We haven't been running the tests, which would've told us about one real broken link (my fault) and one not-actually-broken-but-could've-been link.  This commit fixes the errors and also adds a .travis.yml file so that CI can be setup.
Note, once this is merged, the Travis CI integration needs to be setup by the repository owner.
> Fix broken links, add .travis.yml

- _includes/link-to-issues.md
- _includes/references.md
- _posts/en/newsletters/2018-07-24-newsletter.md
One link depends merge of: https://github.com/bitcoin-core/bitcoincore.org/pull/576 (alternatively, link can be removed; it's labeled as TODO).
Includes a few helper functions, as discussed last week.  Also, this week, I clicked through all the links to make sure they pointed at the right thing (sorry about that last week).
#include <feel_free_to_push_to_my_branch>
> Add newsletter #5 2018-07-24

- _posts/en/newsletters/2018-07-24-newsletter.md
Citation link to the summary for the described conversation.
> Newsletter #5: add link to Bitcoin Core weekly meeting

- _layouts/post.html
- _posts/en/2018-07-20-announcing-bitcoin-optech.md
Fixes #37 
~I added the date in parens after _today_. That meant the first sentence had two parens, which felt a bit unwieldy to me. I've moved the _(Optech)_ down to the second paragraph.~
Added a `post` layout and changed the launch post to use it.
> Add date to launch announcement

- _posts/en/newsletters/2018-08-07-newsletter.md
#48 introduced an HTML-Proofer failure in the latest newsletter. Fix it.
> Newsletters: fix HTML-Proofer failure in newsletter #7

- _includes/references.md
- _posts/en/newsletters/2018-08-21-newsletter.md
Note: I'll be AFK most of the day tomorrow (Monday), so please push changes without waiting to hear back from me.  I'll review later in the evening (EDT) when I get home.
> Newsletters: add #9 (2018-08-21)

- _includes/references.md
- _posts/en/newsletters/2018-07-31-newsletter.md
- _posts/en/newsletters/2018-08-28-newsletter.md
> Newsletters: add #10 (2018-08-28)

- _includes/references.md
- _posts/en/newsletters/2018-09-11-newsletter.md
Another slow news week.  I guess everyone is taking time to enjoy either the end of summer or the coming of spring.
Note: for the LND line in the merges section, I didn't see any merges that seemed particularly notable to me but they did seem to put in a lot of work this week, so I described what seemed to be the general trend.
Todo:
> Newsletters: add #12 (2018-09-11)

- _includes/references.md
- _posts/en/newsletters/2018-09-18-newsletter.md
> Newsletters: add #13 (2018-09-18)

- _contrib/clc2b
- _includes/linkers/issues.md
- _includes/references.md
- _posts/en/newsletters/2018-10-02-newsletter.md
Super slow news week, so a short newsletter.  Some notes:
- I was able to find a way to connect C-Lightning commits to PR numbers, so we now include those (see first two commits on this PR)
- I deliberately didn't link to the 0.17 release notes to avoid over-promoting the new release before it's been officially announced.  If the binaries are uploaded before the newsletter is released, it might be worth revising that action item accordingly.
- The LND RPCs are actually written in their code in UpperCamelCase, so I'm just following their convention here (I mention this because I've tried, and failed, in the past to use upper camel case for bitcoind things, but this time I have upstream on myside.  :-)  From the examples I've read, it seems they can be called all-lowercase or case …
> Newsletters: add #15 (2018-10-02)

- _includes/linkers/issues.md
- _includes/references.md
- _posts/en/newsletters/2018-10-23-newsletter.md
A bit wordy and technical this week; I'll try to be more concise and simple next week.
For the nmap results, I'm happy to email or IRC the commands to any of you who want to replicate the test (I just don't like posting exact port scanning commands publicly in order to reduce abuse).
> Newsletters: add #18 (2018-10-23)

- _posts/en/newsletters/2018-10-23-newsletter.md
Oops, as part of the review I fixed a PR number in one place and not the other, causing one of the links not to render.  This fixes it.
> Newsletter #18: fix broken link

- _includes/references.md
- _posts/en/newsletters/2018-10-30-newsletter.md
I'm terribly, terribly sorry this is so late.  :-(
Otherwise, hopefully it's ok.  I won't be around this evening to address feedback, but I will check first thing tomorrow morning (around 06:00 EDT) and make any requested changes then.
> Newsletters: add #19 (2018-10-30)

- Makefile
- _posts/en/2018-07-30-xapo-consolidation.md
This adds a test that should catch the problem that lead to #79.  This is the same test I've [used](https://github.com/bitcoin-core/bitcoincore.org/blob/master/Makefile#L21) in the BitcoinCore.org repository (and Bitcoin.org before it).
This PR also fixes an incidence of a broken ref-style link, although it only occurred in the HTML metadata for an article.  The excerpt used to fix that bug is the same as appears on the site [here](https://bitcoinops.org/en/newsletters/2018/07/24/#coming-attractions).  This should not result in any user-visible changes to the site (and I don't see any in my quick testing).
> Makefile: test for broken reference-style links

- _includes/references.md
- _posts/en/newsletters/2018-11-13-newsletter.md
This week's news is a bit short, but I'm hoping @jnewbery will be inserting a section about the LN Residency talk videos.
@jnewbery I decided against mentioning bitcoin#14437 (prep for separating node and wallet) in the code changes section as it's just preface to the real work---work I certainly do plan to mention when that gets merged (or earlier, if it otherwise becomes newsworthy).  However, I know you're following the progress of the separation more closely than I am, so let me know if you think 14437 should go in this newsletter.
> Newsletters: add #21 (2018-11-13)

- _includes/newsletter-signup.html
- assets/css/mailchimp.css
I lost connectivity for a bit yesterday while proofreading the newsletter via a local preview, where I noticed we were pulling this CSS over the Internet.  I don't think that's necessary, so this just re-hosts the exact same CSS locally.  This not only makes working offline nicer but it also reduces the amount of information about casual visitors to the site that gets disclosed to Mailchimp.
> CSS: use locally-hosted copy of mailchimp signup CSS

- _posts/en/newsletters/2018-12-11-newsletter.md
Our shortest newsletter since October, but still a reasonable length IMO.
Note, for the sighash news item, I sent an email to the bitcoin-dev list skeptically inquiring about whether that feature would actually be useful.  (The email appears to be in moderation as of this PR open.)  It's possible, although probably unlikely, that there will be agreement that it's not useful, at which point this is probably not noteworthy news and should be removed (even though it'll make the newsletter even shorter).
> Newsletters: add #25 (2018-12-11)

- .travis.yml
- _includes/references.md
- _posts/en/newsletters/2019-01-08-newsletter.md
> Newsletters: add #28 (2019-01-08)

- _posts/en/newsletters/2018-12-28-newsletter.md
- assets/css/main.scss
This decreases the text size in the tables slightly and adds horizontal scrollbars to tables that are still too wide.  You can preview the changes using an actual mobile devices at http://dg3.dtrt.org/en/newsletters/2018/12/28/
I guess in the future, though, we'll just have to avoid tables.  :-(
> CSS: shrink tables and handle x overflows

- _includes/linkers/issues.md
- _includes/references.md
- _posts/en/newsletters/2019-01-15-newsletter.md
Slow news week, so a short newsletter.  Some notes:
- This week includes notable merges from Eclair, as suggested previously by Steve and John.  (Just one notable merge this week.)  I'm also monitoring the BIPs and lightning-rfc repositories, but neither has had any merges this year, so I don't mention them yet in the introduction.
- I've dropped links to the GitHub diffs for the different projects this week.  Maintaining that was mildly annoying for me and I suspect nobody was looking at them.
- The versions of Bitcore and Copay mentioned as being affected are my own research---Bitcore by looking at which git tags included the commits Maxwell identified as introducing the vulnerability and the fix; Copay by looking at which versions of its bower.json file depended on which versions of …
> Newsletters: add #29 (2019-01-15)

- .travis.yml
- Gemfile
- Gemfile.lock
- Makefile
- README.md
- _config.yml
- _includes/linkers/issues.md
- _posts/en/2018-07-20-announcing-bitcoin-optech.md
- _posts/en/2018-09-04-dashboard-announcement.md
- _posts/en/newsletters/2018-07-31-newsletter.md
- _posts/en/newsletters/2018-08-07-newsletter.md
- _posts/en/newsletters/2018-08-14-newsletter.md
- _posts/en/newsletters/2018-08-21-newsletter.md
- _posts/en/newsletters/2018-08-28-newsletter.md
- _posts/en/newsletters/2018-09-04-newsletter.md
- _posts/en/newsletters/2018-09-11-newsletter.md
- _posts/en/newsletters/2018-09-18-newsletter.md
- _posts/en/newsletters/2018-09-25-newsletter.md
- _posts/en/newsletters/2018-10-02-newsletter.md
- _posts/en/newsletters/2018-10-09-newsletter.md
- _posts/en/newsletters/2018-10-16-newsletter.md
- _posts/en/newsletters/2018-10-30-newsletter.md
- _posts/en/newsletters/2018-12-04-newsletter.md
This removes the need for the workaround in 71e9fad42cecd44cfc418a5802490cd809703a8d by updating Ruby.  I chose Ruby 2.5.1 because [that's the version](https://packages.ubuntu.com/bionic/ruby2.5) used for Ubuntu 18.04 LTS, so users of that system should, in theory, not even need to use rvm to get a Ruby to build site previews.  I use Debian, not Ubuntu, so I haven't tested that.
This also adds a lint checker suggested by @practicalswift with a single check for extraneous spaces at the end of a line.  I think this is an important rule because some Markdown parsers turn two spaces at the end of a line into a `<br>` tag, complicating review because whitespace at the end of a line is often invisible.  There are plenty of [other rules](https://github.com/markdownlint/markdownlint/blob/master/do …
> Update Ruby version, remove Travis workaround, and add Markdown linter

- _posts/en/newsletters/2019-02-05-newsletter.md
His personal site for verification of correct spelling: https://crypto.stanford.edu/~buenz/
Reported by @sipa (thanks!)
> News #32: fix misspelling of Benedikt Bünz's name

- _config.yml
- _includes/header.html
- _posts/en/2018-07-20-announcing-bitcoin-optech.md
- _posts/en/2018-09-04-dashboard-announcement.md
- _posts/en/2018-12-28-2018-optech-annual_report.md
- _posts/en/newsletters/2018-06-08-newsletter.md
- _posts/en/newsletters/2018-06-26-newsletter.md
- _posts/en/newsletters/2018-07-03-newsletter.md
- en/blog/index.md
- index.md
- newsletters.md
We originally created the homepage for this site before we had any content.  This revamps it a bit by doing the following:
1. Linking to all the content we now have: workshops, newsletters, dashboard, blog posts, and a WIP scaling book.
2. Replaces the "posts" listing on the main page with a link to our most recent content in both the blog and the newsletters, limiting the display to the most recent three items.
3. Adds a new index page for the blog posts and links to it from the main page
4. Displays excerpts for all the newsletters and blog posts.  This required writing a few excerpts for pages that didn't have nice ones by default
I'm biased, but I think it makes the homepage much more approachable if we were to do something like #116
> Revamp index and content listings

- about.md
- index.md
This PR:
- moves the introductory text and sponsors to the about page, making the front page less cluttered
- adds a 'funding' section to the about page (closes #83)
> Update about page

- _config.yml
Closes #133
Validator: https://cards-dev.twitter.com/validator
Test URL: http://dg2.dtrt.org/en/newsletters/2019/04/09/
How this change works: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#setting-a-default-image
> Layout: add default opengraph image

- _posts/en/newsletters/2019-04-30-newsletter.md
- assets/css/main.scss
No news again this week (if you saw anything I missed, let me know and I can maybe write it up quick).  This puts @moneyball's StackExchange writeup verbatim from his doc (converted to markdown and accidentally minus a link) in a separate commit and then puts my edits in a separate commit on top of that so he can easily see what's changed.  If he accepts the changes, those two commits can be squashed down into the one with his authorship info.
> News: add #44 (2019-04-30)

- _posts/en/newsletters/2019-05-14-newsletter.md
One of the participants in this discussion pointed out to me that suggestion on the mailing list was to include both the xpub and the derivation path.
> News46: mention xpub in addition to derivation path

- _contrib/update-newsletter-index-variables
- _includes/linkers/newsletters.md
- _includes/references.md
- _includes/specials/bech32/01-intro.md
- _includes/specials/bech32/02-stats.md
- _includes/specials/bech32/03-python-ref.md
- _includes/specials/bech32/04-ecc.md
- _includes/specials/bech32/05-fee-savings.md
- _includes/specials/bech32/06-stackexchange.md
- _includes/specials/bech32/07-altbech32.md
- _includes/specials/bech32/08-upgradability.md
- _includes/specials/bech32/09-qrcode.md
- _includes/specials/bech32/10-snooze-lose.md
- _posts/en/2019-03-19-bech32-sending-support.md
- _posts/en/newsletters/2019-03-19-newsletter.md
- _posts/en/newsletters/2019-03-26-newsletter.md
- _posts/en/newsletters/2019-04-02-newsletter.md
- _posts/en/newsletters/2019-04-09-newsletter.md
- _posts/en/newsletters/2019-04-16-newsletter.md
- _posts/en/newsletters/2019-04-23-newsletter.md
- _posts/en/newsletters/2019-04-30-newsletter.md
- _posts/en/newsletters/2019-05-07-newsletter.md
- _posts/en/newsletters/2019-05-14-newsletter.md
- _posts/en/newsletters/2019-05-21-newsletter.md
- assets/css/main.scss
Closes #128 
This moves each bech32 sending support section into a separate includable file and then includes each of them in two different places: first, in the newsletter that originally included them; second, in a blog post backdated to the start of our series.  I think this makes the combined content highly accessible, as it's all easily searchable using find-in-page.
This required moving links around and also moving where we included references.md in some previous newsletters (because it contains variable definitions, it must appear before we use those variables, which means including it before the subsequently-included bech32 sections.  However, it can't go at the very top of the file, since that breaks the automatic first-paragraph summary used on the newsletter index page.)
A …
> Blog: add post with all bech32 content to date

- _data/sponsors.yml
- _includes/members.html
Alto Financial have asked (reasonably) for their image to link to their website instead of twitter profile.
Update members include page to take full URL instead of twitter handle.
> 2019 06 change twitter to website link

- Makefile
- _posts/en/2019-06-14-exec-briefing.md
- _posts/en/newsletters/2019-06-19-newsletter.md
- _posts/en/newsletters/2019-06-26-newsletter.md
I've forgotten to add slugs to several posts, breaking the fix added in #156.  This PR adds the missing slugs plus a test so that it shouldn't be possible to omit them accidentally again.
> Posts: add missing slugs and test for their prescence

- _plugins/auto-anchor.rb
- _posts/en/2019-06-14-exec-briefing.md
- _posts/en/newsletters/2018-09-25-newsletter.md
- _posts/en/newsletters/2018-12-28-newsletter.md
- _posts/en/newsletters/2019-03-05-newsletter.md
- _posts/en/newsletters/2019-05-21-newsletter.md
For #167, @bitschmidty suggested to me that we could automatically generate ids for all list items.  This plugin implements that idea by using the summary text we have for most list items to generate the automatic identifier (slug).  The addition of automatic ids can be disabled on a page-by-page basis (or more broadly using the Jekyll config file with path globs) using a `auto_id: false` page config option.
The html proofer called from the Makefile already errors if we accidentally use the same id twice on the same page (overloading it; most browsers will only go to the first occurrence) and this PR includes a few minor content changes to deal with situations where that occurs.
One way to test this PR is to build the site with and without the plugin and then diff the HTML.  E.g.:
```bash …
```
> Plugins: new auto-anchor plugin for to add ids to list items

- _includes/templates/compatibility-page.md
reported by @adamjonas: https://github.com/bitcoinops/bitcoinops.github.io/commit/1d8d779a984321ab53733abfa9b39200e6b85171#r34607728
> fix typo in compatibility-page.md

- _includes/functions/compat-gallery.md
- _includes/templates/compatibility-page.md
- assets/css/main.scss
- en/compatibility.md
Here are a few small tweaks to the compatibility page CSS and generation code (not specific wallets).  Individual commit comments describe the motivation when it's not obvious.
> Compatibility page tweaks

- CONTRIBUTING.md
- README.md
- _config.yml
- en/compatibility.md
This PR adds contributing guidelines for the compatibility matrix as well as the newsletters.
> Adding contributing guidelines

- .travis.yml
Travis build fails if xenial is used because of a bundler/lockfile version mismatch
```
$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
Traceback (most recent call last):
4: from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
3: from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
2: from /home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `<main>'
1: from /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
The command "eval bundle install --jobs=3 --retry=3 --deployment …
```
> [ci] specify xenial and install new version of bundler

- workshops.md
This PR adds both NYC and SF taproot/schnorr workshops to the workshops page.
I have included them as separate workshops even though the topics are the same. That way we can separately detail the attendees as well as thank associated companies for hosting in the respective venues.
> Workshops: add NYC and SF taproot/schnorr workshops

- .travis.yml
- Makefile
- _posts/en/newsletters/2018-09-25-newsletter.md
- img/posts/2019-03-merkle-ambiguity.dot
This adds an extra makefile target that can be run manually before merging to check for any issues mentioned in the source code that haven't been addressed yet.  I don't know how the Netlify integration works, but if it builds by calling `make` or `make all` and fails to upload the built site if `make` returns false, then changing it to use the new `make production` would prevent it from uploading any changes adding FIXMEs to the site.
A second commit here also re-arranges the existing tests so that source-code tests are run before the site build.  As we've been adding more pages to the site, the build has increased to more than a trivial amount of time.  This allows some tests to fail without having to wait for building.
> Add 'make production' to check for unadressed FIXMEs

- assets/css/main.scss
In https://github.com/bitcoinops/bitcoinops.github.io/pull/181#issuecomment-521044085 , @moneyball mentioned that he found the `:target` highlighting a bit confusing.  This maybe makes it more clear that it's just highlighting to help the user identify position by having it fade over time (currently 5 seconds, we could make it longer or shorter).
> CSS: make blue :target highlight fade over 5 seconds

- .travis.yml
- Makefile
- _contrib/travis-check-png-optimized.sh
This adds a check to the `test-before-build` section of the Makefile that tests if a **newly added or changed** PNG is optimized.  <s>The check only runs (i.e. takes time) for PRs on Travis and not locally.</s> Existing PNGs are not checked to keep Travis build time as short as possible.
<s>Thus reviewing this PR could be a bit tricky.</s> To showcase functionality I've created a PR (https://github.com/0xB10C/bitcoinops.github.io/pull/2) on my travis-enabled fork that adds two PNGs. One optimized and one unoptimized. The Travis [build fails](https://travis-ci.com/0xB10C/bitcoinops.github.io/builds/123239599) on the unoptimized PNG. <s> A diligent reviewer could use a similar setup. </s>
```
sh _contrib/travis-check-png-optimized.sh
checking img/optimized.png
checking img/unoptimized.png …
```
> test: Add travis check ensuring PNGs are optimized

- en/compatibility.md
Small suggested tweak that adds color to the compatibility matrix for the *default address* field:
> Compat: color address type

- _data/compatibility/bitcoin-core-wallet.yaml
This PR updates the Bitcoin Core wallet data files with some of the standard prefixes that we agreed upon since initial data file commits.
> Compatibility data: bitcoin core wallet text standardization

- en/compatibility.md
We previously added links to the segwit and RBF subsections on the individual details page, but now that the number of rows in the matrix is growing, I think we should have links to the subsections on the main matrix page too:
> Compat matrix: add links to subsections

- _includes/templates/compatibility/rbf.md
- _includes/templates/compatibility/segwit.md
@dongcarl [pointed out](https://github.com/bitcoinops/bitcoinops.github.io/pull/179#issuecomment-522720655) inconsistencies between the RBF/segwit sections in the template. This PR helps bring them into the same layout.
> Compatibility template changes to standardize rbf/segwit sections

- _includes/templates/compatibility/rbf.md
@harding [had a good suggestion](https://github.com/bitcoinops/bitcoinops.github.io/pull/179#discussion_r315280536) to clarify one of the RBF not tested descriptions based on the details of one of the wallets tested.
> Compatibility RBF replacement text clarification

- en/compatibility.md
Per @harding 's [suggestion](https://github.com/bitcoinops/bitcoinops.github.io/pull/180#discussion_r315442270), this PR removes the conditional for the empty row if a wallet/service did not have a particular test.
> Compatibility template: remove empty row condition

- CONTRIBUTING.md
- _includes/header.html
- _posts/en/2019-08-21-compatibility-matrix.md
- en/compatibility.md
- index.md
This PR now includes the blog post launching the compatibility matrix and other minor changes for the launch.
Still TODO:
> Launch compatibility matrix

- _plugins/auto-anchor.rb
The auto-anchor plugin, when it saw a list item like this:
- [BOLTs #608][] provides a privacy update to [BOLT4][] that makes it
Was creating links with an anchor of `bolts-608-provides-a-privacy-update-to-bolt4` because it was using a greedy match operator.  This PR changes it to use the minimal-match operator `*?`  so it produces the expected anchor of `bolts-608`.
I tested this by diffing the site output before and after this commit and manually reviewing each change:
```bash
make build
cp -a _site _new_site
git reset --hard HEAD^
make build
diff -ru _site _new_site | colordiff | less -R
```
> Plugins: auto-anchor: use smallest match

- _posts/en/newsletters/2019-09-04-newsletter.md
~Based on #218, ignore first commit~
#218 has been merged
> Newsletters: add 62 (2019-09-04)

- _posts/en/newsletters/2018-06-08-newsletter.md
- _posts/en/newsletters/2018-07-03-newsletter.md
- _posts/en/newsletters/2018-07-10-newsletter.md
- _posts/en/newsletters/2018-07-24-newsletter.md
- _posts/en/newsletters/2018-08-21-newsletter.md
- _posts/en/newsletters/2018-09-18-newsletter.md
- _posts/en/newsletters/2018-12-28-newsletter.md
- _posts/en/newsletters/2019-01-29-newsletter.md
- _posts/en/newsletters/2019-03-12-newsletter.md
- _posts/en/newsletters/2019-05-07-newsletter.md
- _posts/en/newsletters/2019-07-10-newsletter.md
- _posts/en/newsletters/2019-07-17-newsletter.md
- _posts/en/newsletters/2019-07-31-newsletter.md
- _posts/en/newsletters/2019-08-07-newsletter.md
- _posts/en/newsletters/2019-08-28-newsletter.md
- _posts/en/newsletters/2019-09-04-newsletter.md
As discussed here: https://github.com/bitcoinops/bitcoinops.github.io/pull/219#discussion_r320321053
> Grammar: remove hyphen from "Partially-Signed"

- _includes/references.md
- _posts/en/newsletters/2019-09-18-newsletter.md
> Newsletters: add 64 (2019-09-18)

- _posts/en/newsletters/2019-10-02-newsletter.md
> Newsletter 66: correct Eclair DLP bullet

- _layouts/newsletter.html
- _layouts/post.html
- assets/css/main.scss
- assets/css/post.css
Suggested [here](https://github.com/bitcoinops/bitcoinops.github.io/pull/167#discussion_r333611118)
I tested by quickly clicking around a site preview and looking at various page titles to make sure they looked reasonably good.  The only page I didn't really like was About, I think because it's title is so short.  I think it's ok to just live with that slight ugliness in order to get nice, centered titles on all other pages.
> Style: make all h1s centered

- _posts/en/newsletters/2019-10-16-newsletter.md
> Newsletters: add 68 (2019-10-16)

- Makefile
- _config.yml
- _contrib/new-topic
- _contrib/schema-validator.rb
- _data/schemas/topics.yaml
- _includes/header.html
- _includes/linkers/request-a-topic.md
- _includes/linkers/topic-pages.md
- _layouts/topic.html
- assets/css/main.scss
- en/publications.md
- en/topic-categories.md
- en/topic-dates.md
- en/topics.md
This PR adds a page `/en/topics` that provides a hand-curated index to topics we frequently mention in our newsletters and other content.  To allow for incremental deployment of this new feature, similar to what we did with the compatibility matrix, the Topics entry only appears in in the page-top navigation if the site is built with `JEKYLL_ENV=future make preview` (or another make target using the same environment variable).
This PR currently includes 40 topics and some edits to add anchor points for them in the final two commits ("add topics" and "edit content for more anchors").  Those don't need to be reviewed in this PR, they're only attached to make it possible to see what the index pages will look like and to allow exploring the different features of the templates.  When this PR …
> Indexes: add topics index

- _posts/en/newsletters/2019-10-23-newsletter.md
> Newsletters: add 69 (2019-10-23)

- Makefile
- _includes/specials/bech32/06-stackexchange.md
- _includes/specials/bech32/17-signmessage.md
- _posts/en/newsletters/2018-07-31-newsletter.md
- _posts/en/newsletters/2018-08-14-newsletter.md
- _posts/en/newsletters/2018-09-18-newsletter.md
- _posts/en/newsletters/2018-09-25-newsletter.md
- _posts/en/newsletters/2018-10-16-newsletter.md
- _posts/en/newsletters/2018-10-30-newsletter.md
- _posts/en/newsletters/2018-11-13-newsletter.md
- _posts/en/newsletters/2018-11-27-newsletter.md
- _posts/en/newsletters/2018-12-18-newsletter.md
- _posts/en/newsletters/2018-12-28-newsletter.md
- _posts/en/newsletters/2019-01-29-newsletter.md
- _posts/en/newsletters/2019-02-12-newsletter.md
- _posts/en/newsletters/2019-02-26-newsletter.md
- _posts/en/newsletters/2019-03-05-newsletter.md
- _posts/en/newsletters/2019-03-26-newsletter.md
- _posts/en/newsletters/2019-04-02-newsletter.md
- _posts/en/newsletters/2019-04-30-newsletter.md
- _posts/en/newsletters/2019-05-07-newsletter.md
- _posts/en/newsletters/2019-05-29-newsletter.md
- _posts/en/newsletters/2019-06-12-newsletter.md
- _posts/en/newsletters/2019-06-26-newsletter.md
- _posts/en/newsletters/2019-07-31-newsletter.md
- _posts/en/newsletters/2019-08-28-newsletter.md
This PR makes the newsletter content pass the tests described [here](https://github.com/bitcoinops/bitcoinops.github.io/pull/232#discussion_r332799560) and then adds those tests to the makefile.  By putting those bullet titles all on one line, they're automatically turned into anchors by a plugin added in a previous PR.
In a final commit, several anchors are manually added.  Content in the not-yet-added topics branches refers to those anchors.
> Fix bullet titles and add anchors

- _config.yml
- _layouts/newsletter.html
- assets/css/main.scss
- en/publications.md
- feed.xml
- index.md
- newsletters.md
Changes:
- on individual newsletter pages, show available translations, if they exist
- filters on homepage for only english posts
- filters on newsletter page for english posts
- supports language additions
- small fix to newsletter layout html
Notes:
- translations will be located in _posts/[language-code]/newsletters/
- only handles newsletter types for now
- simple language codes (en, ja) for selecting translations. can consider flags or other visuals as well.
Testing:
- add a '_posts/ja/newslettes/2019-10-23-newsletter-ja.md'
- see example ja newsletter here: https://github.com/cryptogarageinc/bitcoinops.github.io/blob/newsletter-69/_posts/ja/newsletters/2019-10-23-newsletter-ja.md
> Adds simple localization features

- _includes/functions/localization-finder.md
- _layouts/newsletter.html
- _layouts/post.html
- en/blog/index.md
Changes:
- on individual blog pages, show available translations, if they exist
- filters on blog page for english posts only
Notes:
- translations will be located in _posts/[language-code]/ , similar to newsletters
- to test, add a '_posts/ja/2019-10-29-schnorr-taproot-workshop.md' file duplicating '_posts/en/2019-10-29-schnorr-taproot-workshop.md' content but changing lang to 'ja' and setting slug and name to '2019-10-21-schnorr-taproot-workshop-ja' 
- Im not happy with duplication of code on the `_layouts/post.html` template when compared to `_layouts/newsletter.html` @harding let me know if you think there is an improvement here
> Adds localization features to blog

- _includes/templates/compatibility/rbf.md
- en/compatibility.md
- Handle missing RBF data in compatibility files in the list template
- Handle missing RBF data in compatibility files in the details template
For background see: https://github.com/bitcoinops/bitcoinops.github.io/pull/257
> Compatibility: Add RBF data conditionals to templates

- _includes/references.md
- _topics/en/assumeutxo.md
- _topics/en/compact-block-filters.md
- _topics/en/countersign.md
- _topics/en/cpfp-carve-out.md
- _topics/en/cve-2018-17144.md
- _topics/en/erlay.md
- _topics/en/generic-signmessage.md
- _topics/en/hwi.md
- _topics/en/miniscript.md
- _topics/en/minisketch.md
- _topics/en/output-script-descriptors.md
- _topics/en/psbt.md
- _topics/en/replace-by-fee.md
- _topics/en/reproducible-builds.md
- _topics/en/transaction-pinning.md
- _topics/en/v2-p2p-transport.md
Eight proposed pages for the new `/en/topics/` section of the site.  Suggested reviewer is @jnewbery 
Note: tests expected to fail on the final "production" test because of the FIXME link pointing to a topic that's part of a different PR.  That's the last test we run, so if it's the only failure, this should be ok.
> Topics: add new topics (jnewbery)

- _includes/references.md
- _posts/en/newsletters/2018-12-28-newsletter.md
- _topics/en/coinjoin.md
- _topics/en/eltoo.md
- _topics/en/mast.md
- _topics/en/payjoin.md
- _topics/en/schnorr-signatures.md
- _topics/en/sighash_noinput.md
- _topics/en/taproot.md
- _topics/en/tapscript.md
Eight proposed pages for the new `/en/topics/` section of the site.  Suggested reviewer is @moneyball  
Note: tests expected to fail on the final "production" test because of the FIXME link pointing to a topic that's part of a different PR.  That's the last test we run, so if it's the only failure, this should be ok.
> Topics: add new topics (moneyball)

- _posts/en/2019-10-29-schnorr-taproot-workshop.md
- _posts/ja/2019-10-29-schnorr-taproot-workshop-ja.md
This adds a link to the respective notebook on Google Colab for each chapter. The same links where added to the Taproot/Workshop README in https://github.com/bitcoinops/taproot-workshop/pull/158.
I did choose "Run this notebook **in** Google Colab" over "Run this notebook **on** Google Colab". I not sure what is better.
My Japanese isn't good enough to add it to the Japanese translation of the workshop page.
> Add links to Google Colab notebooks to Taproot Workshop page

- assets/css/main.scss
- en/topic-dates.md
Instead of showing the same entry for each topic it belongs to, e.g.:
- Tapscript—Bitcoin Optech schnorr/taproot workshop
- Taproot—Bitcoin Optech schnorr/taproot workshop
- Schnorr signatures—Bitcoin Optech schnorr/taproot workshop
This PR combines related entries into a single item, e.g.:
- Bitcoin Optech schnorr/taproot workshop
Tapscript, Taproot, Schnorr signatures
I think it's already the case that the date index looks a little bit silly with duplicated entries.  As we increase the number of topics, I expect more entries to be part of multiple topics and so duplication will increase.  I think the solution in this PR will help keep the date index concise and non-ridiculous looking.
The solution combines entries that have the same date and the same URL, using the title of the …
> Topics: combine related entries on date index

- _config.yml
- _layouts/blog.md
- _layouts/publications.md
- _posts/es/2019-10-29-schnorr-taproot-workshop.md
- es/blog.md
- es/newsletters.md
- es/publications.md
Also adds Spanish as a supported language on the site.
First commit makes minor changes to where the RSS link is placed on the publications/blog indexes, and only shows it for the english indexes.
> Add Spanish translation of the Schnorr/Taproot blog post

- .travis.yml
- removes bundle install directive
- adds a 'yes |' to gem update, essentially passing 'yes' to [a prompt regarding bundle install version overwriting](https://travis-ci.org/bitcoinops/bitcoinops.github.io/builds/625881136#L245), which was freezing (and thus failing) the build previously
Tests via:
- Travis
- Netlify builds
- Netlify build output looks correct: https://deploy-preview-299--bitcoinops.netlify.com/ 
- `make production` build successfully, locally
- `make preview` runs successfully, locally
closes https://github.com/bitcoinops/bitcoinops.github.io/issues/300
> Travis Build Changes

- _contrib/new-topic
- _includes/references.md
- _topics/en/bech32.md
- _topics/en/coin-selection.md
- _topics/en/compact-block-filters.md
- _topics/en/cpfp-carve-out.md
- _topics/en/cpfp.md
- _topics/en/erlay.md
- _topics/en/multipath-payments.md
- _topics/en/musig.md
- _topics/en/psbt.md
- _topics/en/schnorr-signatures.md
- _topics/en/signet.md
- _topics/en/taproot.md
- _topics/en/trampoline-payments.md
- _topics/en/transaction-bloom-filtering.md
- en/topic-categories.md
- Topic updates
- Four new topics (one per newsletter published in November)
- A one-line bugfix and a one-line template tweak
> Topics: November update and new topics

- _posts/en/newsletters/2019-12-28-newsletter.md
BIP70 (and all dependencies) and OpenSSL have been fully removed from master,
which will become 0.20.0.
> BIP70 was not fully removed in 0.19.0.1, just compiled out by default

- _posts/en/newsletters/2019-03-05-newsletter.md
This newsletter correctly calls the function `FindAndDelete()` in most places, but for some reason I used the wrong name in three other places.
Just to make sure I hadn't forgotten something I knew during the writing of the newsletter, I checked both the Bitcoin Core source code and bip-cleanup to confirm that neither mentions a `FindAndReplace()` function.
> News 36: typo fix: s/FindAndReplace/FindAndDelete/

- _posts/es/newsletters/2019-11-27-newsletter.md
Kindly contributed by Bitso.
One paragraph is missing from the original:
> New LND mailing list and new host of existing mailing lists: a new mailing list hosted by Google Groups was announced for LND application developers, with an initial post by Olaoluwa Osuntokun describing short-term goals for LND’s next release. Separately, the existing mailing lists for Bitcoin-Dev and Lightning-Dev have recently had their hosting transferred to Oregon State University’s Open Source Lab (OSL), a well-respected organization that provides hosting to a variety of open source projects. Optech extends our thanks to Warren Togami, Bryan Bishop, and everyone else involved in maintaining all of Bitcoin’s many open communication channels, without which this newsletter wouldn’t exist.
I've followed up with …
> Newsletters: translate 74 into Spanish

- _posts/en/newsletters/2019-06-26-newsletter.md
Git grepping returns no instance of "setwalletflags" in Bitcoin Core.
According to git blame, the `setwalletflag` RPC was added in https://github.com/bitcoin/bitcoin/commit/f904723e0d5883309cb0dd14b826bc45c5e776fb and named as such from the start.
> news52: fix rpc setwalletflag

- Makefile
- _includes/newsletter-signup.html
- _posts/en/newsletters/2019-12-28-newsletter.md
- workshops.md
In https://github.com/bitcoinops/bitcoinops.github.io/pull/318#pullrequestreview-343402308 , @bitschmidty noted that several links were linking to the table of contents rather than the actual content.  This occurred because we had multiple elements set to the same anchor, e.g the table of contents anchor was `<a id="miniscript">` and the actual section about miniscript was `<div id="miniscript">`.
In this PR, all duplicate instances of duplicate anchors are removed by renaming all but one of the elements.  Additionally, a test is added to the Makefile to prevent the problem from recurring.
> Eliminate duplicate anchors from all pages

- _plugins/auto-anchor.rb
Closes #325 
"I think we really want to prefer [using] the first bold string, italics string or link in the list element for the anchor id."  --@jnewbery
Tested by:
1. Running on the otherwise-broken a0a10288208d1925906d62522acd0f154e1b090b (tests passed)
2. Diffing the HTML site output before and after this commit (based on latest master).  This change only introduces three changed anchors, and all of them are good changes IMO.
> Plugins: use shortest match in auto-anchors.rb

- _config.yml
- _data/localization/es.yml
- _data/localization/ja.yml
- _includes/linkers/breadcrumbs.md
- _layouts/newsletter.html
- _layouts/page.html
- _layouts/post.html
This PR adds breadcrumbs to pages that are more than one level removed from the home page, e.g. "/ home / newsletters /" to a newsletter entry:
Features:
- Can be disabled by putting: `breadcrumbs: false` in the page metadata (YAML header)
- Breadcrumbs can be automatically derived from the page URL, e.g. `/en/topics/anchor-outputs/` automatically gets the breadcrumb "/ home / topics /"
- We can also tweak the breadcrumb if desired, e.g. a newsletter URL is `/en/newsletters/2020/01/22/` but we don't currently have year or month index pages, so instead of creating "/ home / newsletters / 2020 / 01 /", we simply tweak the breadcrumb to create "/ home / newsletters /".  At some later point (maybe issue 100?), I think we probably want to split up our index by year, at which point we can …
> Layout: add breadcrumbs to pages >1 level deep

- en/topic-categories.md
- en/topic-dates.md
- en/topics.md
This PR makes three changes to the topic index pages
Each page gets a single line subtitle with some basic statistics about that page, e.g.:
> - 44 topics (and 26 aliases in italics for topics with alternative names).
> - 212 indexed events in 18 months 
> - 17 categories for 44 unique topics, with many topics appearing in multiple categories.
The alphabetical and category indexes get a condensed table of contents linking to the various subheads below, e.g.:
A table of contents for the date index is currently commented out as it links to December 2019, which won't be added until #318 is merged (and it won't really make sense until the January 2020 topics update is merged, so I'll uncomment it in that PR).
We just changed the layout on this page last month in #283, but looking at the huge …
> [Topics] Change date index layout, add stats, add internal page links

- _posts/en/newsletters/2020-02-05-newsletter.md
Parts of the change suggested by @sipa
> News83: update description of verifying sigs before publishing them

- _topics/en/covenants.md
Closes #338 
Broken link identified by @moneyball (thanks!)
Note: we have a couple other links to this same old proposed BIP in newsletter issues that aren't updated in this PR.  Based on the context of the newsletters, I think pointing to an actually assigned BIP would be confusing, so I think it's best to leave them broken.  (But feel free to disagree, or to open a separate issue to discuss what to do about hard-to-point-anywhere-else broken links.)
> Topics: Covenants: update CTV link to point to BIP119

- STYLE.md
- _posts/en/newsletters/2020-02-12-newsletter.md
> Newsletters: add 84 (2020-02-12)

- en/tools/calc-size.md
This adds a crude Javascript-based transaction size calculator to `/en/tools/calc-size/`.  No links are added to the tool from other parts of the site and I'm not sure we should add any unless the tool is improved.  
However, I've found it good enough for my own use and I think it might help y'all when you're burdened with verifying my transaction size math in newsletter and workbook content.  Future improvements can let it deal with a wider range of multisig variations, differing types of input and output scripts, non-keypath P2TR, uncompressed pubkeys, low-R signatures, LN onchain scripts, and other common transaction types.
That said, if you don't think this is a good fit for the Optech website, let me know and I can easily host it somewhere else.
> Tools: add crude calculator for transaction size

- _includes/references.md
- _posts/en/newsletters/2020-02-05-newsletter.md
- _posts/en/newsletters/2020-02-19-newsletter.md
> Newsletters: add 85 (2020-02-19)

- _config.yml
Closes #350 
Corrects validation errors that turned out to be only because of missing defaults from the configuration file.  This changes the metadata on every page on the site, but besides that and the desired change to the feed.xml file, the only visible change I see is a slight tweak to the page footer (it goes from saying "Bitcoin Optech" to "Bitcoin Operations Technology Group"; I can suppress that change if desired).
Validation results on a test build of this commit: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fdg0.dtrt.org%2Ffeed.xml
(The remaining warning only applies because the test URL is different from the production URL.)
> Feed: correct validation errors

- CONTRIBUTING.md
> CONTRIBUTING.md : adds detail around internal linking for translations

- _includes/references.md
- _topics/en/op_codeseparator.md
fixes https://github.com/bitcoinops/bitcoinops.github.io/issues/347
I left the following untouched as the link to the _transaction digest_ section is [no longer up to date](https://github.com/sipa/bips/commit/c0d2f93f3c3c3dcee2318ea26f946ae17de37865#diff-506cf22853a59a8c57550c1f1d9cedfb). I'll let you to decide how to follow up with this one.
https://github.com/bitcoinops/bitcoinops.github.io/blob/f3f9b7a1bc833cba0f8d31a167d6a86c0abba9ff/_topics/en/op_codeseparator.md#L110-L111
> change: link to offical BIPs for BIP340-342

- _includes/references.md
- _posts/en/newsletters/2020-03-18-newsletter.md
> Newsletters: add 89 (2020-03-18)

- Makefile
The Makefile for this project was copied from bitcoin.org, where
incremental builds didn't work because of their custom plugins.
Therefore, the build was cleaned for every preview.
We don't have complicated plugins so we can just do an incremental build
for local previews.
Also add a `make clean` target.
This brings preview build times down from ~14s to <1s for me.
> [build] Don't jekyll clean for previews

- _posts/en/newsletters/2019-12-18-newsletter.md
- _posts/en/newsletters/2020-03-25-newsletter.md
Note, we discussed maybe bringing back the Network Activity section because of last week's moderate backlog; however, some of that was caused by the significant drop in hashrate and thus the slower block production---which will mostly change around the time we go to publish because of a retarget, so I decided not to write the section.
> Newsletters: add 90 (2020-03-25)

- Makefile
- _layouts/default.html
- _plugins/auto-anchor.rb
Closes #393 
Related to https://github.com/bitcoinops/bitcoinops.github.io/pull/387#pullrequestreview-390772699 and some internal discussion, I think this small change should make it possible to generate a local preview of the site content that's suitable for copy/pasting into MailChimp for sending the newsletter.
1. Generate a preview normally, e.g. `make preview`
2. Browse to the page you will want to copy/paste
3. Kill the preview server (e.g. Ctrl-C)
4. Generate a fresh preview using the `JEKYLL_ENV=email` environment variable, e.g. `JEKYLL_ENV=email make clean preview` (note: you **need** clean for this)
5. Reload the page in your browser
All the relative links on the site should've been transformed in your browselr from, e.g., `http://localhost:4000/foo/bar` to …
> Preview: allow setting base URI to https://bitcoinops.org

- _posts/en/newsletters/2020-04-29-newsletter.md
> Newsletter 95 (2020-04-29)

- _topics/en/unannounced-channels.md
Adds a new topic.  An unresolved issue is what to call this topic: **unannounced channels** or **private channels**.  The name we choose affects the URL and I *really* don't want to break a URL (or even setup a redirect) if we change names later, so let's try to choose a good term now.
- It's an accurate description of the key attribute of such channels
- It has no particular negative or positive connotations (AFAIK)
- It has use going back to at least [2017](https://lists.linuxfoundation.org/pipermail/lightning-dev/2017-December/000846.html) and a quick search of Lightning-Dev shows it being used by Rusty Russell, Christian Decker, and Bastien Teinturier.  ZmnSCPxj seems to use the related term "unpublished channels".  Those are all significant contributors to LN development and I like …
> Topics: add new topic for unannounced channels

- _posts/en/newsletters/2020-05-20-newsletter.md
> Newsletters: add 98 (2020-05-20)

- _posts/en/newsletters/2018-12-28-newsletter.md
- _posts/en/newsletters/2020-02-05-newsletter.md
- _posts/en/newsletters/2020-05-27-newsletter.md
Note: if there's any further significant discussion on the `<65` byte transaction thread, I'll updated that news item.  I probably should've waited until next week to write about it, but there wasn't any other significant news this week that I saw.
> Newsletters: add 99 (2020-05-27)

- _data/sponsors.yml
Current link is for https://twitter.com/wences , which isn't the person we want.  I can't find an account for Xapo's Casares, so this PR just drops the link.  I checked that the page renders fine without the link.
> About: remove incorrect Twitter link for Casares

- _topics/en/covenants.md
- _topics/en/op_checksigfromstack.md
This brings us to 8/16 topics that I should've submitted by now.
The CSFS, CTV, and Vaults topics all derive somewhat from the existing Covenants topic, but I think it was time for them to each have separate topics.  I've left the Covenants topic for now without any deletions to its existing links, but going forward I plan mainly to only use it for topics that are much more specific to covenants.
> New topics: OP_CHECKSIGFROMSTACK

- _posts/en/newsletters/2020-06-03-newsletter.md
As far as I know the term, as well as in the wiki that is linked, the term discussed here is called the `common input ownership assumption`, and not `common wallet ownership assumption`. 
If I am mistaken here, and `wallet` is the intended word, then please dismiss and close the PR.
---
Congrats on #100 - this is incredible work!
> Change to common *input* ownership assumption

- Makefile
- _includes/articles/towns-xapo-consolidation.md
- _includes/specials/bech32/18-support-issues.md
- _includes/specials/bech32/21-brd.md
- _posts/en/2018-07-20-announcing-bitcoin-optech.md
- _posts/en/2018-09-04-dashboard-announcement.md
- _posts/en/2018-12-28-2018-optech-annual_report.md
- _posts/en/2019-02-11-rbf-in-the-wild.md
- _posts/en/newsletters/2018-07-03-newsletter.md
- _posts/en/newsletters/2018-07-10-newsletter.md
- _posts/en/newsletters/2019-12-28-newsletter.md
- _posts/en/newsletters/2020-01-22-newsletter.md
- _posts/en/newsletters/2020-06-03-newsletter.md
- _posts/ja/newsletters/2019-12-28-newsletter-ja.md
- _posts/ja/newsletters/2020-01-22-newsletter-ja.md
- en/tools/calc-size.md
Using internal URLs makes it easier to locally preview the site.  Additionally, our existing tests only verify the existence of internal URLs so any pages using an external domain name aren't guaranteed to resolve.
Inspired by https://github.com/bitcoinops/bitcoinops.github.io/pull/417#discussion_r437568679
The commit assigning a permalink to the the tx size calculator is needed for this change; see its commit comment for a justification.
> Tests: require using internal URLs for internal content

- _includes/references.md
- _posts/en/newsletters/2019-08-28-newsletter.md
1. updates miniscript link to miniscript topic
2. updates rpc base url to 0.20
If there is a cleaner way to do # 1, please opine, @harding
> Update miniscript, rpc references

- _includes/articles/river-descriptors-psbt.md
- _posts/en/2020-07-29-river-descriptors-psbt.md
- _posts/en/newsletters/2020-07-29-newsletter.md
> Newsletters: add 108 (2020-07-29)

- _layouts/topic.html
We're starting to get some topics with a lot of mentions, which produces a long hard-to-read list.  This PR buckets the entries by year and drops the per-entry date (which is now less important and which was always a bit ugly).  Example:
> Topics: bucket mentions by year

- _includes/references.md
- _topics/en/cve-2018-17144.md
- _topics/en/eltoo.md
- _topics/en/erlay.md
- _topics/en/musig.md
- _topics/en/output-script-descriptors.md
- _topics/en/schnorr-signatures.md
- _topics/en/taproot.md
In last week's newsletter, @bitschmidty [caught](https://github.com/bitcoinops/bitcoinops.github.io/pull/459#discussion_r492166331) me accidentally linking directly to Wuille's miniscript page rather than the Optech topic page I wanted.  This happened because, prior to the addition of the topics page, I had defined some quick reference links for highly-referenced subjects; obviously, many of those subjects later became topics.
This PR deprecates those old links.  On pages with dates in the past, the old link definitions will be used.  On pages with newer dates (or no dates at all, like the topic pages), the old link definitions aren't evaluated and so the hyperlink won't be generated, causing the post-build test to fail---hopefully ensuring I insert the appropriate topic link (or …
> References: deprecated some old quick links

- CONTRIBUTING.md
- feed.xml
Useful for reviewing changes to site-generating code.
Not sure if it's worth packaging this up into a script?
> Add local site diff'ing instructions

- _posts/en/newsletters/2020-10-14-newsletter.md
- _topics/en/adaptor-signatures.md
- _topics/en/addr-v2.md
- _topics/en/anchor-outputs.md
- _topics/en/bech32.md
- _topics/en/signet.md
- _topics/en/spontaneous-payments.md
Note: per [this discussion](https://github.com/bitcoinops/bitcoinops.github.io/pull/460#issuecomment-697287888), we're going to try making updates to the topic index in the newsletters that add the noteworthy content.  Reviewers not interested in those updates can skip reviewing those additions (or anything else you want to skip, of course!).  Please let me know if you think this is creating too much churn on the PR or has other problems---I'm happy to try something else.
> Newsletters: add 119 (2020-10-14)

- _includes/references.md
Current link throws 404. So updating to latest ANYPREVOUT BIP link.
> Links: update ANYPREVOUT BIP link

- _posts/en/newsletters/2020-11-25-newsletter.md
During the multiple edits of this writeup, I didn't notice that the unit of the new `fee_rate` was removed, without which it no longer makes sense in the writeup why `fee_rate` was added.
I also didn't notice that "option" was removed in favor of parameter only, which is somewhat incorrect, as `fee_rate` is an option, not a param, in several of the changed RPCs.
- re-add "denominated in sat/vB"
- re-add "option"
> news125: PR 20305 fixup

- STYLE.md
The goal here was to standardize on "sat/vbyte" as our preferred unit for feerates, but this required rewriting the main item for currency units.
> Style: update currency abbreviations, including for feerates

- Makefile
- _topics/en/ptlc.md
It seems I accidentally added the same link to the PTLCs topic twice (it was that exciting!).  This replaces the redundancy with a different link and adds a test to hopefully stop me from doing it again.
> Topics: replace duplicate entry in PTLCs

- _includes/references.md
- _posts/en/newsletters/2020-03-04-newsletter.md
- _posts/en/newsletters/2020-12-16-newsletter.md
- _topics/en/addr-v2.md
- _topics/en/anchor-outputs.md
- _topics/en/bech32.md
- _topics/en/eclipse-attacks.md
- _topics/en/output-script-descriptors.md
- _topics/en/psbt.md
- _topics/en/replace-by-fee.md
- _topics/en/transaction-pinning.md
@bitschmidty [last year](https://bitcoinops.org/en/newsletters/2019/12/18/), you did both the monthly client/services section and the monthly Bitcoin StackExchange section in our last regular newsletter of the year.  Please feel free to do that again if you want, but no pressure if you don't.
> Newsletters: add 128 (2020-12-16)

- Makefile
- STYLE.md
- _contrib/kill0
- _posts/en/newsletters/2019-05-14-newsletter.md
This fixes a couple puny problems.  h/t @Xekyo
> Spelling: s/discrete/discreet/ for DLCs

- _posts/en/newsletters/2020-12-23-newsletter.md
Reported by @ajtowns .  Git grep shows no other incidences of this misspelling.
> Typo fix: spelling of Lloyd Fournier's name

- _posts/en/newsletters/2021-02-10-newsletter.md
- _topics/en/bech32.md
- _topics/en/generic-signmessage.md
- _topics/en/psbt.md
- _topics/en/taproot.md
~~My stuff isn't finished on this yet, sorry, but I hope to get it done early Monday UTC-10.  I suggest deferring reviews until I take this out of draft---I wanted to get the PR open so y'all'd be able to add your own contributions.~~
> Newsletters: add 135 (2021-02-10)

- en/topic-dates.md
This allows the [topic date index](https://bitcoinops.org/en/topic-dates/) to display entries after 2020.
> Topics: date index: display entries after 2020

- _posts/en/newsletters/2021-03-03-newsletter.md
- _topics/en/bip70-payment-protocol.md
- _topics/en/hwi.md
> Newsletters: add 138 (2021-03-03)

- _includes/functions/sort-rename.md
- en/topics.md
Because our style guide says not to insert prefix zeros into BIP names (a style I strongly prefer), the topic names and aliases for BIPs were sorting in an unexpected order, e.g. BIP125 appearing before BIP70.  This PR should fix that; screenshot below of live site compared to this commit.
> Topics template: sort BIPs in expected order

- _posts/en/newsletters/2020-12-23-newsletter.md
- _topics/en/soft-fork-activation.md
I think this is really putting the `extended` in the `extended_summary` field.  I can probably publish this excessive amount of detail about past soft fork attempts somewhere else if y'all think this should be more focused.
I also think this could maybe do a better job of describing current activation proposals, but they're all still being actively discussed and so I'm not sure it's worth writing about them now only to have to change it in a week or a month.  (Maybe that's why I geeked out about nice, static history.)
> New topic: Soft Fork Activation

- _posts/en/newsletters/2021-04-07-newsletter.md
- _topics/en/dual-funding.md
Wow, nothing for me to write this week.  I'll keep looking over the weekend, but I'm not expecting much.
> Newsletters: add 143 (2021-04-07)

- _topics/en/bech32.md
Bech32 only allows uppercase or lowercase, but mixed case is explicitly forbidden. Thus, calling it case insensitive is a bit inaccurate.
> Topic: Clarify that Bech32 is case sensitive

- Makefile
It sometimes trips me up when I run `make preview` locally and don't see new newsletters/topic pages/blog posts in the index page.
> [build] Delete all index pages in `make preview`

- _topics/en/psbt.md
- _topics/en/replace-by-fee.md
This addresses two comments from @jnewbery regarding the topic links in Newsletter 149.  I do leave unaddressed a couple comments from John about the newsletter content itself, but I think of newsletter content as being mostly static once published, while the topic pages are dynamic.
> Topics: improve topic descriptions added in Newsletter 149

- _posts/en/newsletters/2018-08-14-newsletter.md
- _posts/en/newsletters/2018-08-28-newsletter.md
- _posts/en/newsletters/2018-09-04-newsletter.md
- _posts/en/newsletters/2018-09-11-newsletter.md
- _posts/en/newsletters/2018-09-18-newsletter.md
- _posts/en/newsletters/2018-09-25-newsletter.md
- _posts/en/newsletters/2018-11-27-newsletter.md
- _posts/en/newsletters/2019-04-23-newsletter.md
Closes #576 
When we first started covering C-Lightning merged PRs, their method of "merging" by rebasing PRs on top of their master branch didn't directly provide me the information necessary to attribute the correct PR on GitHub.  Later, I developed a script that took a commit ID and found the PR, so we've been printing C-Lightning PR numbers for the past two years (almost).
This PR revises the old C-Lightning listings to use their PR numbers.  In a couple cases, this required consolidating multiple entries from different commits into a single PR entry.  I also fixed a couple other cases to work with our auto-linking plugin, since they were found my my grep command `vi $( git grep -l '^- C-L' )`.
I had to find the commits referenced in our descriptions using a combination of (1) our …
> Newsletters: update legacy references to C-Lightning PRs

- _data/schemas/topics.yaml
- _posts/en/newsletters/2021-06-02-newsletter.md
- _topics/en/output-script-descriptors.md
- _topics/en/package-relay.md
- _topics/en/schnorr-signatures.md
- _topics/en/taproot.md
Addresses these comments:
https://github.com/bitcoinops/bitcoinops.github.io/pull/581#discussion_r643768463
https://github.com/bitcoinops/bitcoinops.github.io/pull/581#discussion_r643774700
plus (from my memory) some previous complaints about recent too-short titles.
> Topics: increase max title length and use the extra space (also a News151 fixup)

- en/tools/calc-size.md
The overall cost to create and spend a P2TR output is essentially the same as P2WPKH but the division of the costs between inputs and outputs is quite different, with P2TR being closer to symmetric than P2WPKH.  This means our default of a 1-input-2-output transaction gives a misleading impression that P2TR is much more expensive than P2WPKH.
This PR changes the default transaction template to use 2 inputs and 2 outputs, which eliminates the confusion.
(Thanks to someone reading a Reddit thread about this for reporting it to me.)
> Calc-size: default to 2-in-2-out

- STYLE.md
Opinions welcome.  Previous comments:
@harding
> [7:08:25 pm] <harding> Style guide question for taproot: "key path"/"script path", "key-path"/"script-path", or "keypath"/"scriptpath" (or something else).  BIP341 uses the space versions; I think I'm partial to the single word versions (but no strong preference).  No rush.
@jnewbery 
> [10:28:40 pm] <jnewbery> No strong preference, but my initial reaction is that as those terms become more common, we'll naturally want a single symbol to represent them (ie keypath/scriptpath), much like public key turned into pubkey once it became a common term.
@jonatack 
> I prefer "key path" and "script path"
Current repository state (not counting references in newsletter 154, since those were made despite Jon stating a different preference; also …
> Style: compound words: keypath & scriptpath

- Makefile
- _includes/specials/taproot/en/03-p2wpkh-to-p2tr.md
- _posts/en/2021-06-23-preparing-for-taproot.md
- _posts/en/newsletters/2021-07-14-newsletter.md
- _topics/en/bech32.md
- _topics/en/block-explorers.md
- _topics/en/offers.md
- _topics/en/op_checksigfromstack.md
- _topics/en/output-script-descriptors.md
- _topics/en/schnorr-signatures.md
- _topics/en/sighash_noinput.md
Note: the news section links to a mailing list post of mine; extra scrutiny of that item welcome!
> Newsletters: add 157 (2021-07-14)

- _includes/specials/taproot/en/05-taproot-notebooks.md
- _posts/en/2021-06-23-preparing-for-taproot.md
- _posts/en/newsletters/2021-07-28-newsletter.md
- _topics/en/dual-funding.md
- _topics/en/psbt.md
- _topics/en/reproducible-builds.md
Note: the entry about dual-funding/liquidity advertisements support for "sidecar channels" is currently unverified.  I think my reasoning about it is sound, but I asked for confirmation in `#lightning-dev` IRC.
> Newsletters: add 159 (2021-07-28)

- _posts/en/newsletters/2021-07-28-newsletter.md
I added an extra decimal point somehow.  Guess I have to turn in my shadowy super coder club card now.  :-(
Thanks @amitiuttarwar for reporting!
> News159: new addr rate limit is 4x measured rate, not 40x

- _includes/head.html
- _includes/specials/bech32/05-fee-savings.md
- _includes/specials/bech32/06-stackexchange.md
- _includes/specials/bech32/07-altbech32.md
- _includes/specials/bech32/11-only-bech32.md
- _includes/specials/bech32/12-midway.md
- _includes/specials/bech32/21-brd.md
- _includes/specials/bech32/23-compat.md
- _includes/specials/taproot/en/01-single-sig.md
- _includes/specials/taproot/en/02-descriptors.md
- _includes/specials/taproot/en/03-p2wpkh-to-p2tr.md
- _includes/specials/taproot/en/04-why-wait.md
- _includes/specials/taproot/en/05-taproot-notebooks.md
- _plugins/auto-anchor.rb
Closes #604 
Apparently it's a known limitation of Jekyll that Liquid template processing doesn't work on `{% include %}` files, which is why the automatic bullet linking isn't working.  This PR adds a `{% auto_anchor %}...{% endauto_anchor %}` block filter that we can put in included files in order to run the anchoring code manually (including calling Liquid).
To test this by diffing the site, I found it necessary to temporarily disable the SEO plugin which outputs a non-deterministic entry in the header of every page.  There's already a bug for that upstream.  (I don't know why this just became a problem now; I've diffed plenty of times before without problems.)  Temporarily disabling the SEO plugin required adding the template from Jekyll Minima to our repository, which is the first …
> Layout: Add auto bullet linking to included files

- _contrib/new-topic
- _includes/snippets/stub-topic.md
- _layouts/topic.html
- _topics/en/asicboost.md
- _topics/en/atomic-multipath.md
- _topics/en/exfiltration-resistant-signing.md
- _topics/en/hd-key-generation.md
- _topics/en/multipath-payments.md
- _topics/en/payment-secrets.md
- _topics/en/rendez-vous-routing.md
- _topics/en/segregated-witness.md
- _topics/en/side-channels.md
- _topics/en/signer-delegation.md
- _topics/en/static-channel-backups.md
- _topics/en/timelocks.md
Adds stub topic pages for all qualifying topics from our spreadsheet tracker and this repository's open issues.  (Qualifying means at least three mentions and doesn't have other issues.)
There are several benefits to having stub descriptions for topics:
- It makes our content more accessible, even if only te people who already know what the topic is about
- We can start linking to the new pages immediately, building backlinks
- If a topic isn't worth hosting a page for, someone can complain before too much effort has been invested in writing about it
- Maybe other people will be interested in expanding stub descriptions into full writeups
h/t to @jnewbery who suggested elements of this approach
> Topics: add stub descriptions for all currently qualifying proposed topics

- STYLE.md
The symbol for kibi is "Ki" with a capital k. Since the International
System of Units restricts the use of SI prefixes strictly to powers of
10, the description of that line is updated to not mention SI in the
context.
> Correct symbol for kibibyte

- _includes/specials/taproot/en/11-vaults-with-taproot.md
- _posts/en/2021-06-23-preparing-for-taproot.md
- _posts/en/newsletters/2021-09-08-newsletter.md
- _topics/en/anchor-outputs.md
- _topics/en/coin-selection.md
- _topics/en/compact-block-relay.md
- _topics/en/output-script-descriptors.md
- _topics/en/psbt.md
- _topics/en/vaults.md
Huge thanks to @darosior for the contributed taproot section this week!
> Newsletters: add 165 (2021-09-08)

- _includes/linkers/issues.md
- _includes/references.md
Can be tested by:
- In any newsletter from the past two years, click the "Lightning BOLTs" link in the *Notable changes* section
- In the newsletters returned by the following grep, scrolling to the *Notable changes* section and clicking the link for "BOLTs #xxx" `git grep -l -- '- \[BOLTs' | xargs grep '^title: '`
You could also diff the built site from before and after the change; I was too lazy to do that.  (Maybe if I'm ever not lazy, I'll add generating a diff to the CI script.  Don't hold y'alls breath though :smile:)
> Links: update to use new lightning/bolts repo

- _posts/en/newsletters/2021-12-01-newsletter.md
- _topics/en/anchor-outputs.md
- _topics/en/bech32.md
- _topics/en/hwi.md
- _topics/en/output-script-descriptors.md
- en/topic-dates.md
> Newsletters: add 177 (2021-12-01)

- _posts/en/newsletters/2021-12-15-newsletter.md
- _topics/en/ptlc.md
- _topics/en/uneconomical-outputs.md
> Newsletters: add 179 (2021-12-15)

- _posts/en/newsletters/2021-12-22-newsletter.md
- _topics/en/atomic-multipath.md
- _topics/en/bech32.md
- _topics/en/channel-jamming-attacks.md
- _topics/en/dual-funding.md
- _topics/en/offers.md
- _topics/en/onion-messages.md
- _topics/en/output-script-descriptors.md
- _topics/en/package-relay.md
- _topics/en/ptlc.md
- _topics/en/replace-by-fee.md
- _topics/en/sighash_anyprevout.md
- _topics/en/signet.md
- _topics/en/taproot.md
Still some minor items to finish before this PR is complete, but the text is ready for review.  I did leave myself a few optional todos if I have some spare time and want to make this a bit longer.
> Newsletters: add 180 (2021-12-22)

- _topics/en/output-script-descriptors.md
Came across these 2 topic `optech_mentions` titles that were malformed (missing opening quote).
I did not run a scan of other topics for mismatched quotes (some entries have no quotes and work fine)
> Topic: Descriptors: fixups

- _includes/linkers/issues.md
- _posts/en/newsletters/2022-01-19-newsletter.md
- _posts/en/newsletters/2022-02-09-newsletter.md
- _posts/ja/newsletters/2022-01-19-newsletter.md
- _topics/en/psbt.md
- _topics/en/replace-by-fee.md
Sorry for opening the PR late!
> Newsletters: add 186 (2022-02-09)

- _topics/en/transaction-pinning.md
The [existing wording](https://bitcoinops.org/en/topics/transaction-pinning/) could easily be misunderstood as the minimum absolute fee needed to equal just the highest paying transaction ("any"), instead of the sum of all fees of the replaced transaction and its children, as it is described in [BIP125](https://github.com/bitcoin/bips/blame/master/bip-0125.mediawiki#L56). I think this proposal makes it less ambiguous.
> Transaction Pinning: emphasize that the sum of fees needs to be replaced

- _posts/en/newsletters/2022-04-06-newsletter.md
- fix link to the doc (from jonatack/bitcoin to bitcoin/bitcoin, and to a commit that includes the update merged yesterday)
- add a second pull merged yesterday that covers the most frequent issue users have been running into
- maybe remove link to anonymity networks section (cjdns is an `fc00::/8` reserved IPv6 range overlay network with e2e encryption but does not hide the sender and the recipient from intermediate routers)
Happy to update or drop some of these, per feedback.
> Newsletter 194 cjdns entry fixups

- _includes/linkers/issues.md
- _includes/references.md
- _posts/en/newsletters/2022-04-13-newsletter.md
- _topics/en/cpfp.md
- _topics/en/miniscript.md
- _topics/en/musig.md
- _topics/en/stateless-invoices.md
Note: I asked Rusty whether he preferred "Core Lightning" or "CLN" and went with his choice.  I may use CLN instead in cases where we're character-limited.
> Newsletters: add 195 (2022-04-13)

- Makefile
This updates the Makefile to rebuild indices of all languages so that translated articles and links to other languages show up in previews.
Note that I have never worked with Makefiles before, so I'm just taking a stab in the dark here—although it did seem to achieve the desired effect.
> Rebuild indices for all languages on preview

- _posts/de/newsletters/2022-08-10-newsletter.md
*default minimum transaction relay feerate* has been translated to *Standardminimumgebührenrate für Transaktionsweiterleitungen*, which imho is a bit convoluted and might confuse native German speakers. Same goes for *opt-in* / *standardmäßigen Einwilligung (opt-in)*. I wasn't able to come up with a more concise translation. 
There's probably a story for creating a small reference sheet with terms that should be used in their English native form.
> Newsletter 212: Translate to German

- _topics/en/soft-fork-activation.md
It should be “billion” instead of “million”
> Correct amount temporarily created in overflow bug

- _posts/de/newsletters/2022-08-10-newsletter.md
Caused a missing bullet which is unlinkable in future references (like https://github.com/bitcoinops/bitcoinops.github.io/pull/843/files#diff-a621ae1e11f09c21fcec55111f696ebbe0627357553f2c4fd21a0f15b3e7e39aR134)
> News212: German translation format fix

- _posts/de/newsletters/2022-09-07-newsletter.md
The translation on this one is a bit bumpy. 
- _work_ has been translated to _Arbeitsnachweise_ to provide more context
- _Header_ was left in its original form since _Blockkopf_ or _Kennsatz_ sounded too verbatim.
Thanks for the review and suggestions.
> Newsletter-216: Translate to German

- _data/compatibility/edge.yaml
Nothing changed, except that segwit v1 displays an error now:
https://user-images.githubusercontent.com/6399679/195279428-d965b88f-dff4-4b4d-ab4e-c46025c2293d.jpg
(Didn't update the screenshots because I only have JPGs and changes seemed minimal)
> compat: Update edge

- _posts/en/newsletters/2022-11-02-newsletter.md
- _topics/en/anchor-outputs.md
- _topics/en/compact-block-filters.md
- _topics/en/compact-block-relay.md
- _topics/en/cpfp.md
- _topics/en/erlay.md
- _topics/en/hwi.md
- _topics/en/low-r-grinding.md
- _topics/en/offers.md
- _topics/en/psbt.md
- _topics/en/rendez-vous-routing.md
- _topics/en/replace-by-fee.md
- _topics/en/v2-p2p-transport.md
> Newsletters: add 224 (2022-11-02)

- STYLE.md
Check this PR -- I'm unsure if "zero-conf" is the convention we actually want. LMK if not and I can update this PR. The command
```
$ grep -i zero.*conf _posts/en/*/*md
```
shows several forms, `zero-conf`, `zeroconf`, and `zero conf`, so we haven't been very consistent.
> add zero-conf to compound words list

- _topics/en/responsible-disclosures.md
This adds a responsible disclosure we previously reported on but which I missed in compiling the entries for the initial topic page.  My appologies to @renepickhardt
I plan to merge shortly after the tests pass.
> Topics: responsible disclosures: add 2020 fee ransom attack

- _posts/en/newsletters/2022-11-23-newsletter.md
> Newsletters: add 227 (2022-11-23)

- _posts/en/newsletters/2022-11-23-newsletter.md
The link name says rc2, but the link goes to rc1
> News227 fixup: Link to right RC

- _posts/cs/newsletters/2022-11-30-newsletter.md
Translation of 228 into Czech.
I dared to add two additional links (`news20{1,4} package relay`) pointing to information about package relays in Czech translations of the newsletter. Some links (Wiki, semver) point to Czech versions.
> Newsletter-228: Translate into Czech

- _topics/en/coin-selection.md
I was made aware that the link titled “Simulation-based Evaluation of Coin Selection Strategies” on the Coin Selection page was broken. I removed wordpress from my website earlier this year and added a softlink for my thesis from the old location of the file to the new, but didn't realize that someone might link to my 2-page talk proposal for Scaling Bitcoin, so I broke that link.
My Scaling Bitcoin talk proposal was moved from http://murch.one/wp-content/uploads/2016/09/CoinSelection.pdf to https://murch.one/CoinSelection.pdf.
However, I was wondering whether this was perhaps meant to be a link to my thesis instead: https://murch.one/erhardt2016coinselection.pdf
> Fix broken link to coin selection work

- _posts/en/newsletters/2022-12-07-newsletter.md
- _topics/en/anchor-outputs.md
- _topics/en/transaction-pinning.md
- _topics/en/version-3-transaction-relay.md
\* This is one week earlier than normal because we'll be publishing our year-in-review newsletter on 12/21 and won't be publishing on 12/28, and Larry was kind enough to agree to doing his summary early so we can try to fit all our regular monthly sections in for December.
> Newsletters: add 229 (2022-12-07)

- _posts/en/2023-03-08-podcast.md
- _posts/en/newsletters/2023-03-08-newsletter.md
- _topics/en/covenants.md
- _topics/en/soft-fork-activation.md
- _topics/en/vaults.md
Also adds a blog post announcing the podcast.
> Newsletters: add 241 (2023-03-08)

- _topics/en/ephemeral-anchors.md
BIP/implementation was changed after enough people got confused: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-March/021536.html
> Switch ephemeral anchors to OP_TRUE

- _posts/en/newsletters/2023-03-29-newsletter.md
I missed this link in review so we should link to the official repo
> News244: fix rust bitcoin release notes link

- _includes/functions/podcast-callout.md
- _includes/functions/podcast-note.md
- _includes/newsletter-references.md
- _plugins/auto-anchor.rb
- _plugins/common_utils.rb
- _plugins/recap_references_generator.rb
- _posts/en/newsletters/2023-02-15-newsletter.md
- _posts/en/newsletters/2023-02-22-newsletter.md
- _posts/en/newsletters/2023-03-01-newsletter.md
- _posts/en/newsletters/2023-03-08-newsletter.md
- _posts/en/newsletters/2023-03-15-newsletter.md
- _posts/en/newsletters/2023-03-22-newsletter.md
- _posts/en/newsletters/2023-03-29-newsletter.md
- _posts/en/newsletters/2023-04-05-newsletter.md
- _posts/en/newsletters/2023-04-12-newsletter.md
- _posts/en/podcast/2023-02-16-newsletter-recap.md
- _posts/en/podcast/2023-02-23-newsletter-recap.md
- _posts/en/podcast/2023-03-02-newsletter-recap.md
- _posts/en/podcast/2023-03-09-newsletter-recap.md
- _posts/en/podcast/2023-03-16-newsletter-recap.md
- _posts/en/podcast/2023-03-23-newsletter-recap.md
- _posts/en/podcast/2023-03-30-newsletter-recap.md
- _posts/en/podcast/2023-04-06-newsletter-recap.md
- _posts/en/podcast/2023-04-13-newsletter-recap.md
- _posts/zh/newsletters/2023-03-08-newsletter.md
This PR removes the need for boilerplate logic when adding newsletter references. The new logic requires just the podcast timestamps to be added in the related newsletter sections.
**Current logic**:
- In the podcast, recreate the newsletter structure:
- add title and anchor for each discussed item
- add timestamp
- add anchors for each segment in the transcript 
- In the referenced newsletter, for each item, add a link to the podcast page
**New logic**:
- In the podcast:
- point to the newsletter it references using the `reference` variable in the frontmatter
- In the referenced newsletter:
- add timestamp (podcast reference mark) for each discussed item
For each podcast, the `recap_references_generator` will parse the `reference` newsletter (declared in frontmatter) looking for podcast …
> Podcast: simplify newsletter references

- _includes/functions/podcast-note.md
- _includes/newsletter-references.md
- _plugins/recap_references_generator.rb
The current logic in `recap_references_generator.rb` doesn't work when a section does not have nested list items, which is the case with the recent special sections in newsletters [250](https://bitcoinops.org/en/newsletters/2023/05/10/#celebrating-optech-newsletter-250) and [251](https://bitcoinops.org/en/newsletters/2023/05/17/#waiting-for-confirmation-1-why-do-we-have-a-mempool). This first became visible with #1122 and that's why this PR is on top of that one, in order to be able to see the change in action. @bitschmidty feel free to either cherry-pick my commits in your PR, or you can merge this one, whatever you prefer.
This is how those special sections will be rendered in the recap podcast page:
> Podcasts: fix automatic reference generation for special sections

- _posts/en/newsletters/2023-05-24-newsletter.md
Looks like a typo. Would we want to be consistent with the [Taproot topic](https://bitcoinops.org/en/topics/taproot/) and call it "keypath spend" instead?
> Change keysend to keyspend in 2023-05-24-newsletter.md

- _includes/templates/compatibility/rbf.md
- _topics/en/responsible-disclosures.md
Fixes a typo introduced with a recent pull request
> Fix typo in compatibility matrix

- _posts/en/newsletters/2023-08-30-newsletter.md
- _topics/en/covenants.md
- _topics/en/musig.md
- _topics/en/op_checksigfromstack.md
- _topics/en/op_checktemplateverify.md
- _topics/en/rendez-vous-routing.md
- _topics/en/responsible-disclosures.md
- _topics/en/sighash_anyprevout.md
- _topics/en/watchtowers.md
Note: brings back a PR description by @murchandamus that was dropped from last week's newsletter [due to a misunderstanding](https://github.com/bitcoinops/bitcoinops.github.io/pull/1250#discussion_r1302848218) (sorry!).
> Newsletters: add 266 (2023-08-30)

- _posts/en/newsletters/2023-09-13-newsletter.md
- _topics/en/client-side-validation.md
- _topics/en/miniscript.md
- _topics/en/ptlc.md
- _topics/en/v2-p2p-transport.md
> Newsletters: add 268 (2023-09-13)

- _posts/ja/newsletters/2023-09-13-newsletter.md
About lnd release, there seems to be a tag for [v0.17.0-beta.rc3](https://github.com/lightningnetwork/lnd/releases/tag/v0.17.0-beta.rc3), can we keep rc2?
> Newsletter-268:Translate into Japanese

- _posts/en/newsletters/2023-09-20-newsletter.md
It is "Tracer", not "Trace", and also "Elements", not "Element"
> Fix mistypes in B'SST description in 2023-09-20-newsletter.md

- _includes/references.md
- _posts/en/newsletters/2023-11-01-newsletter.md
> Newsletters: add 275 (2023-11-01)

- _includes/articles/wizardsardine-miniscript.md
- _includes/snippets/recap-ad.md
- _posts/cs/newsletters/2023-11-01-newsletter.md
- _posts/en/2023-11-15-wizardsardine-miniscript.md
- _posts/en/newsletters/2023-11-01-newsletter.md
- _posts/en/newsletters/2023-11-08-newsletter.md
- _posts/en/newsletters/2023-11-15-newsletter.md
- _posts/fr/newsletters/2023-11-01-newsletter.md
- _posts/fr/newsletters/2023-11-08-newsletter.md
- _posts/ja/newsletters/2023-11-01-newsletter.md
- _posts/ja/newsletters/2023-11-08-newsletter.md
- _posts/zh/newsletters/2023-11-01-newsletter.md
- _topics/en/cpfp.md
- _topics/en/ephemeral-anchors.md
- _topics/en/jit-channels.md
- _topics/en/miniscript.md
Note: this  PR parameterizes the advertisement for the spaces that we began including two newsletters ago.  The new version uses basically the same text but should automatically stop displaying the ad on a particular newsletter the first time the site is built after the spaces is scheduled to begin.  Let me know if anyone disagrees with that behavior.  In accordance with that behavior, this PR also manually deletes the add from the previous two newsletters.
> Newsletters: add 277 (2023-11-15)

- _posts/en/newsletters/2023-11-22-newsletter.md
- _topics/en/offers.md
Note: we're planning to do the spaces recap on Wednesday (22 Nov) instead of the usual Thursday due to U.S. thanksgiving.  (Maybe we want to publish the newsletter on Tuesday?  I'm ok with that.)
> Newsletters: add 278 (2023-11-22)

- Makefile
- _posts/en/newsletters/2023-02-22-newsletter.md
Also adds a test to catch future incidents.
> Fix: add missing code delimiters for timestamp in News239

- _posts/en/newsletters/2023-12-13-newsletter.md
- _topics/en/liquidity-advertisements.md
- _topics/en/payjoin.md
- _topics/en/psbt.md
> Newsletters: add 281 (2023-12-13)

- .travis.yml
One does not simply remove the command that is required in order to not break the builds but which is also currently breaking the builds
But it works(?)
> Build: remove Travis CI bundler update directive

- _posts/en/newsletters/2023-12-20-newsletter.md
Of course seconds after merging, I notice that the url/slug/permalinks are 2022.
> News282: update urls

- _posts/en/newsletters/2024-01-03-newsletter.md
- _topics/en/channel-factories.md
- _topics/en/cluster-mempool.md
- _topics/en/coin-selection.md
- _topics/en/joinpools.md
- _topics/en/onion-messages.md
- _topics/en/output-script-descriptors.md
- _topics/en/payment-batching.md
- _topics/en/psbt.md
- _topics/en/rendez-vous-routing.md
- _topics/en/responsible-disclosures.md
- _topics/en/timelocks.md
- _topics/en/transaction-pinning.md
- _topics/en/unannounced-channels.md
- _topics/en/version-3-transaction-relay.md
> Newsletters: add 283 (2024-01-03)

- _posts/en/newsletters/2024-01-10-newsletter.md
- _topics/en/anchor-outputs.md
- _topics/en/eltoo.md
- _topics/en/ephemeral-anchors.md
- _topics/en/out-of-band-fees.md
- _topics/en/version-3-transaction-relay.md
Also, there's a PR with some new topics originally intended for last week's newsletter at #1452
> Newsletters: add 284 (2024-01-10)

- _posts/en/newsletters/2024-01-17-newsletter.md
- _topics/en/anonymity-networks.md
- _topics/en/ark.md
- _topics/en/cluster-mempool.md
- _topics/en/cpfp-carve-out.md
- _topics/en/ephemeral-anchors.md
- _topics/en/op_checksigfromstack.md
- _topics/en/op_checktemplateverify.md
- _topics/en/rendez-vous-routing.md
- _topics/en/responsible-disclosures.md
- _topics/en/v2-p2p-transport.md
- _topics/en/version-3-transaction-relay.md
Includes Ark topic that was previously in #1452
> Newsletters: add 285 (2024-01-17)

- _posts/en/newsletters/2024-01-17-newsletter.md
Follow-up to #1468, I was unavailabale to review pre-merge
> small spelling and grammar fixups to news285

- _includes/newsletter-references.md
- _posts/en/newsletters/2023-12-20-newsletter.md
- _posts/en/podcast/2023-12-21-newsletter-recap.md
- assets/css/main.scss
Adds 282 year in review podcast:
- Adds bullets to the year in review which makes the automated podcast referencer work and look nice
- Replaced the newlines in the callouts with colons, and reverse "Summary" and "2023" for link generation purposes (example: “Summary 2023: Bitcoin Optech”)
- Tweaked part of the note-to-self comments in the Bitcoin Optech callout which was borking the podcast parser.
- Small change to newsletter-references to omit the “no news found…” text for the YiRs.
Possible additional change includes changing the YiR ToC to use the bullet link vs custom anchors. Ive kept both, except where there were duplicates, for now since some people may be linking to the original YiR ToC anchors.
If this works, I will apply the same for YiR 2022 ([open …
> Podcast: add 282 recap

- _posts/en/newsletters/2024-01-03-newsletter.md
- _topics/en/acc.md
- _topics/en/expiration-floods.md
- _topics/en/fee-estimation.md
- _topics/en/matt.md
Based on #1451 ; this PR is only for the last commit.
I had a  bunch of topic pages I wanted to add for Newsletter 283 but I think they need some review before we publish, so I'm opening this PR instead.  Included is an edit to News283 to include the links to the topic pages.  That slightly violates our no-significant-edits-after-publication policy, but that newsletter was really meant to link to these topics, so I think that's ok.
> Topics: add multiple topics for Newsletter 283

- topics.json
Exporting topics in a JSON format allows **seamless utilization of this well-thought-out resource by anyone**.
After this change, the topics (alongside their metadata) will be available at `https://bitcoinops.org/topics.json`
Example of exported JSON:
```
[
{
"title": "Accountable Computing Contracts",
"slug": "acc",
"optech_url": "https://bitcoinops.org/en/topics/acc/",
"categories": [
"Contract Protocols"
],
"aliases": [
"BitVM",
"Zero-Knowledge Contingent Payments (ZKCP)"
],
"excerpt": "**Accountable Computing Contracts (ACC)** are payments that the receiving party can spend if they verifiably run a specified function on a specified set of inputs.  If the receiving party doesn't run the function or doesn't run it correctly, the paying party can reclaim the payment after a period of …
```
> Topics: export as JSON

- _includes/references.md
- _includes/specials/taproot/en/19-future.md
- _posts/en/newsletters/2021-02-03-newsletter.md
- _posts/en/newsletters/2021-07-14-newsletter.md
- _posts/en/newsletters/2022-03-09-newsletter.md
- _posts/en/newsletters/2022-05-18-newsletter.md
- _topics/en/op_cat.md
- _topics/en/op_checksigfromstack.md
It was previously a subsection of OP_CSFS.  This separation was suggested in #721
> Topics: separate OP_CAT into its own topic page

- _topics/en/eltoo.md
closes https://github.com/bitcoinops/bitcoinops.github.io/issues/1525
I thought the wording suggested in https://github.com/bitcoinops/bitcoinops.github.io/issues/1525 made sense.
> Topic: Eltoo rewording

- STYLE.md
The term blockchain has become accepted since the style guide was written in 2019. There are already significantly more instances of "blockchain" than "block chain" in this repository.
> Prefer blockchain over block chain

- _posts/en/newsletters/2018-10-09-newsletter.md
- _posts/en/newsletters/2019-04-23-newsletter.md
- _posts/en/newsletters/2019-06-19-newsletter.md
- _posts/en/newsletters/2019-09-04-newsletter.md
- _posts/en/newsletters/2020-03-04-newsletter.md
- _posts/en/newsletters/2021-04-28-newsletter.md
- _posts/en/newsletters/2022-08-17-newsletter.md
- _posts/en/newsletters/2022-12-21-newsletter.md
- _posts/en/newsletters/2023-06-28-newsletter.md
- _posts/en/newsletters/2023-08-02-newsletter.md
- _posts/en/newsletters/2023-10-04-newsletter.md
- _posts/en/newsletters/2023-11-29-newsletter.md
- _posts/en/podcast/2022-08-18-newsletter-recap.md
- _posts/en/podcast/2022-08-25-newsletter-recap.md
- _posts/en/podcast/2022-12-01-newsletter-recap.md
- _posts/en/podcast/2023-01-26-newsletter-recap.md
- _posts/en/podcast/2023-02-02-newsletter-recap.md
- _posts/en/podcast/2023-08-10-newsletter-recap.md
- _posts/en/podcast/2023-08-17-newsletter-recap.md
- _posts/en/podcast/2023-09-07-newsletter-recap.md
- _posts/en/podcast/2023-11-30-newsletter-recap.md
Fixes multiple instances where hyphens are used instead of en dashes in names created by joining the names of authors, such as Diffie–Hellman or Boneh–Lynn–Shacham.
> Replace hyphens with en dashes

- _data/compatibility/bitgo.yaml
- _posts/en/newsletters/2024-03-20-newsletter.md
- _topics/en/kindred-replace-by-fee.md
- _topics/en/miniscript.md
- _topics/en/psbt.md
- _topics/en/replace-by-fee.md
- _topics/en/simplicity.md
- _topics/en/splicing.md
- _topics/en/v2-p2p-transport.md
> Newsletters: add 294 (2024-03-20)

- _posts/en/newsletters/2024-04-10-newsletter.md
- _topics/en/acc.md
- _topics/en/coin-selection.md
- _topics/en/rendez-vous-routing.md
- _topics/en/taproot.md
@stickies-v here's the source to last month's review club section for reference: https://raw.githubusercontent.com/bitcoinops/bitcoinops.github.io/master/_posts/en/newsletters/2024-03-13-newsletter.md  Please don't hesitate to ask here, on IRC, or wherever if you have any questions.  Thanks for writing!  (And many thanks to @LarryRuane for his excellent work on this section every month since Aug 2022!)
> Newsletters: add 297 (2024-04-10)

- _posts/zh/newsletters/2018-08-07-newsletter.md
- _posts/zh/newsletters/2018-08-14-newsletter.md
- _posts/zh/newsletters/2018-08-21-newsletter.md
- _posts/zh/newsletters/2018-08-28-newsletter.md
- _posts/zh/newsletters/2018-09-04-newsletter.md
- _posts/zh/newsletters/2018-09-11-newsletter.md
- _posts/zh/newsletters/2018-09-18-newsletter.md
- _posts/zh/newsletters/2018-09-25-newsletter.md
- _posts/zh/newsletters/2018-10-02-newsletter.md
- _posts/zh/newsletters/2018-10-16-newsletter.md
#1552 was opened about a month ago to remove github-log.md
Several translations of old newsletters were made after that.
I then merged #1552 without checking that it built on master, which led to a build failure.  Sorry!  This fixes it.
> Fix use of now-removed github-log.md

- _topics/en/cve.md
- _topics/en/responsible-disclosures.md
Also add a link from Responsible Disclosures to CVEs
Note: I also wanted to add one of the CVE numbers for the replacement cycling attack, but those are still only reserved, e.g. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-40231
(Also, I think I probably messed up with the CVE page.  The goal was to have a page that described all major security disclosures that have been discussed by Optech, but some things we've discussed this year (e.g. Matt Moorehouse's fake channels DoS disclosure) don't have CVEs.  I think in a future topic update we should look at creating a new page that includes everything have have the CVEs page redirect to it.)
> Topics: CVEs: add Milksad CVE number

- Makefile
- _posts/fr/newsletters/2024-02-21-newsletter.md
- _posts/fr/newsletters/2024-03-06-newsletter.md
- _posts/fr/newsletters/2024-03-13-newsletter.md
- _posts/fr/newsletters/2024-03-27-newsletter.md
- _posts/fr/newsletters/2024-04-03-newsletter.md
- _posts/fr/newsletters/2024-04-10-newsletter.md
- _posts/fr/newsletters/2024-04-17-newsletter.md
Part of #1551
Some of our posts contain an extra space in the YAML header between a key and value, e.g.:
title : 'Bulletin Hebdomadaire Bitcoin Optech #290'
Jekyll strips the extra space, so the key becomes `title`.  Hugo preserves the extra space, so the field doesn't work as expected.
This PR eliminates the extra space in the source file and adds a test to help avoid future extra spaces.
> Posts: check YAML formatting

- _posts/en/newsletters/2024-05-17-newsletter.md
- _topics/en/acc.md
- _topics/en/async-payments.md
- _topics/en/channel-announcements.md
- _topics/en/codex32.md
- _topics/en/htlc.md
- _topics/en/onion-messages.md
- _topics/en/silent-payments.md
**Goal is for Friday email distribution to some of our readers.**  Other readers will receive it on Monday. See #1641 for details.  This is a soft goal; if we miss it, we'll try again next week.
Because this is (I hope) a Friday release and there are two subsequent Fridays in the month, there's no Client/Services section this week.  If we don't permanently move to Fridays, we might have to do a double client/services+stack exchange section.
Upfront thanks to everyone for helping with this experiment and for being willing to consider an alternative publication date!
> Newsletters: add 303 (2024-05-17)

- _topics/en/x-only-public-keys.md
there is a minor issue with the `see_also` key
resulting in broken YAML and "Schnorr signatures"
to not be displayed in the ["See also" section](https://bitcoinops.org/en/topics/x-only-public-keys/).
> fix YAML for `x-only-public-keys`

- _includes/references.md
- _posts/en/newsletters/2024-06-07-newsletter.md
- _topics/en/covenants.md
- _topics/en/onion-messages.md
- _topics/en/op_cat.md
- _topics/en/testnet.md
- _topics/en/time-warp.md
- _topics/en/v2-p2p-transport.md
- _topics/en/version-3-transaction-relay.md
> Newsletters: add 306 (2024-06-07)

- _posts/en/newsletters/2024-06-14-newsletter.md
> News307: correct description of Bitcoin Core 28979

- STYLE.md
- _posts/en/newsletters/2024-06-28-newsletter.md
- _topics/en/anchor-outputs.md
- _topics/en/channel-commitment-upgrades.md
- _topics/en/coin-selection.md
- _topics/en/package-relay.md
- _topics/en/replace-by-fee.md
- _topics/en/silent-payments.md
- _topics/en/x-only-public-keys.md
> Newsletters: add 309 (2024-06-28)

- _posts/zh/newsletters/2019-05-29-newsletter.md
#1802 used old links that were replaced in #1809.  This fixes that.
I plan to merge once tests pass.
> ZH News48: fix links broken by previous commit

- en/about.md
I missed references to the original home of the scaling book, https://github.com/bitcoinops/scaling-book, in reviewing https://github.com/bitcoinops/bitcoinops.github.io/pull/1830 (apologies!)
This commit removes the most obvious version of that in about.md but there are 3 more (sans localizations):
- _posts/en/2018-12-28-2018-optech-annual_report.md
- _posts/en/2019-02-11-rbf-in-the-wild.md
- _posts/en/newsletters/2019-12-28-newsletter.md
If we plan to leave the scaling book repo, these references are probably fine to leave. Feedback welcome.
> Scaling book reference cleanup

- _topics/en/client-side-validation.md
RGB doesn't use pay-to-contract commitment scheme since 2022. I also fixed use of term "associates" to "assigns", as a valid technical term - and added information about single-use seals.
> Client-side validation: fix terminology

- _topics/en/time-warp.md
Fixes #1859 
Also amends the maximum block production rate to 6 blocks per second.
> Fix duration of second epoch in time warp description

- _topics/en/block-withholding.md
I believe there's a typo in the first paragraph of the [block-withholding](https://bitcoinops.org/en/topics/block-withholding) entry, i.e. it seems to me that the paragraph should actually be like below:
> ... where a miner submits and receives payment for shares that are not eligible to become full blocks but doesn’t submit shares that are eligible to become full blocks. ...
Is this the case?
> block-withholding: remove excerpt double negation.

- _posts/en/newsletters/2024-09-20-newsletter.md
- _topics/en/anonymity-networks.md
- _topics/en/assumeutxo.md
- _topics/en/async-payments.md
- _topics/en/channel-announcements.md
- _topics/en/cluster-mempool.md
- _topics/en/coin-selection.md
- _topics/en/consensus-cleanup-soft-fork.md
- _topics/en/discreet-log-contracts.md
- _topics/en/fee-estimation.md
- _topics/en/merkle-tree-vulnerabilities.md
- _topics/en/offers.md
- _topics/en/onion-messages.md
- _topics/en/op_cat.md
- _topics/en/output-script-descriptors.md
- _topics/en/pooled-mining.md
- _topics/en/psbt.md
- _topics/en/sidechains.md
- _topics/en/silent-payments.md
- _topics/en/uneconomical-outputs.md
> Newsletters: add 321 (2024-09-20)

- _topics/en/ark.md
- _topics/en/op_checktemplateverify.md
Alternative to #1811 
The current text for the CTV page entirely dates from May 2020.  This complete rewrite of the page provides additional details about it, both from the original proposal and from the subsequent years of discussion.
> Topics: update CTV to cover 4+ years of discussion

- _posts/en/newsletters/2024-10-25-newsletter.md
- _topics/en/channel-announcements.md
- _topics/en/psbt.md
- _topics/en/silent-payments.md
- _topics/en/simple-taproot-channels.md
- _topics/en/splicing.md
- _topics/en/v2-p2p-transport.md
> Newsletters: add 326 (2024-10-25)

- _includes/functions/podcast-bullet.md
- _includes/functions/podcast-note.md
- _includes/newsletter-references.md
- _posts/en/podcast/2024-10-31-deepdive-superscalar.md
Two commits here
First one is a refactor of the podcast linking includes so I can reuse component in an non-newsletter podcast.
I tried to keep the diff small including spacing, but you can check using the commands: (provided in another PR by @harding)
1. Checkout this branch
2. Build the tip: make clean all (all tests should pass except the fixme)
3. Backup the generated site: cp -a _site _new_site
4. Checkout the merge root, something like git reset --hard HEAD^2
5. Build the site again: make clean build
6. Diff the resultant HTML: diff -ruN _site _new_site | colordiff | less -R
Second adds the SuperScalar podcast. I am using dropbox to host the audio file before publication, so the timestamp seeking might be slow.
Current publication targeting for 10/31.
If there are better ways to …
> Podcast: add SuperScalar Deep Dive

- en/tools/calc-size.md
Adds an explanation for the signature size and mentions that low-r grinding wallets will produce smaller signatures consistently.
> calc-size: Clarify conservative signature size

- _topics/en/lnurl.md
Pretty self-explanatory. The "primary code" link on this page is broken. https://bitcoinops.org/en/topics/lnurl/
> lnurl: Fix link to LNURL Documents (LUDs)

- _topics/en/mast.md
- _topics/en/schnorr-signatures.md
- _topics/en/taproot.md
- _topics/en/threshold-signature.md
This hopefully removes all remaining mentions of taproot, schnorr signatures and MAST that describe them as _proposed_ additions to Bitcoin.
Better late than never.
> Update topics to reflect taproot activation

- _topics/en/soft-fork-activation.md
**easy changes:**
`INT64_MAX` is `9223372036854775807` (`2**63-1`)
`INT64_MIN` is `-9223372036854775808` (`-2**63`)
**other changes:**
For whatever reason, post # 1 in [bitcointalk topic 822](https://bitcointalk.org/index.php?topic=822.0) contains a different output amount than post # 3  
`post #1: 92233720368.54277039 (0x7ffffffffff863af)`  
`post #3: 92233720368.54275808 (0x7ffffffffff85ee0)`  
I'm assuming post # 3 ist right, because it's `2**63-500000`, and the sum of outputs is a round number: -0.01 BTC (minus 1 million sats). (calculation: `9223372036854275808*2 - 2**64 = -1000000`)
> fix amounts in overflow bug description

- _topics/en/swap-in-potentiam.md
Adding a potentiam as a topic.
> Topics: Add Swap-in Potentiam (SIP)

- _posts/de/newsletters/2025-01-31-newsletter.md
- Add German translation for Newsletter #339
- Format text to have 80-100 characters per line
- Remove trailing whitespace
> Add German translation for Newsletter #339

- en/tools/reorg-calculator.md
This PR adds a new tool that shows the probability that an attacker with a given percentage of the total network hashrate could successfully execute a block reorganization of a given depth. 
The current implementation matches the mathematical model presented in the Bitcoin whitepaper (Chapter 11) and is similar to Greg Maxwell's [online calculator](https://web.archive.org/web/20190201183912/https://people.xiph.org/~greg/attack_success.html) 
The tool also:
- Uses pure JS (no-dependencies)
- Follows similar approach/styling to the existing Transaction Size Calculator
Note: the PR is marked as draft because it currently implements the original whitepaper formula. 
This will be updated to match the calcultion described in [Double Spend …
> tools: Add reorg calculator

- _includes/header.html
- _includes/specials/bech32/02-stats.md
- _includes/specials/bech32/zh/02-stats.md
- _posts/en/2018-09-04-dashboard-announcement.md
- _posts/en/2018-12-28-2018-optech-annual_report.md
- _posts/en/2019-02-11-rbf-in-the-wild.md
- _posts/en/2021-02-19-pausing-memberships.md
- _posts/en/newsletters/2018-08-07-newsletter.md
- _posts/en/newsletters/2018-08-14-newsletter.md
- _posts/en/newsletters/2018-12-28-newsletter.md
- _posts/en/newsletters/2021-10-20-newsletter.md
- _posts/zh/2019-02-11-rbf-in-the-wild.md
- _topics/en/replace-by-fee.md
- en/about.md
- index.md
It appears that the dashboard is defunct, so for now it probably makes sense to remove the links to it.
> Remove links to dashboard

- _includes/references.md
- _posts/en/newsletters/2025-03-07-newsletter.md
- _topics/en/discrete-log-equivalency.md
- _topics/en/ephemeral-anchors.md
- _topics/en/quantum-resistance.md
- _topics/en/responsible-disclosures.md
- _topics/en/simple-taproot-channels.md
- _topics/en/soft-fork-activation.md
- _topics/en/wallet-labels.md
> Newsletters: add 344 (2025-03-07)

- _posts/en/newsletters/2025-03-21-newsletter.md
- _topics/en/ark.md
- _topics/en/ecash.md
- _topics/en/fee-estimation.md
- _topics/en/htlc.md
- _topics/en/pooled-mining.md
- _topics/en/replace-by-fee.md
- _topics/en/replacement-cycling.md
- _topics/en/threshold-signature.md
- _topics/en/transaction-pinning.md
I might also add something about the testnet3 discussion on the ML, but I see AntoineP just started a related thread, so I'm inclined to let that stew for a few days and summarize it next week.
> Newsletters: add 346 (2025-03-21)

- _data/matrix/Nunchuk.yaml
Source: https://bitcoinops.org/en/newsletters/2025/01/24/#nunchuk-adds-taproot-musig2-features
> matrix: Record Nunchuk’s MuSig2 support

- en/matrix.md
Sorry, [I linked to the old section name](a9a9771ad0e7182816ab164ab6cb1b685f87d269) on the compatibility page and overlooked that the matrix pull request changed the title of the corresponding section.
> Fix link to Feature Matrix contributions

- en/matrix.md
Howdy....in the matrix,  the **Key Features / Use Cases** are provided as free text by the "submitters".  With this change, that free text appears in quotes and italics, to emphasise that the text was bot provided by bitcoin optech.
> add quotes/italics 2 features

- _posts/en/newsletters/2025-06-20-newsletter.md
- _topics/en/acc.md
- _topics/en/attributable-failures.md
- _topics/en/musig.md
- _topics/en/peer-storage.md
- _topics/en/pooled-mining.md
Note: I added a description of an Rust Libsecp256k1 merge to the notable merge section by request.
> Newsletters: add 359 (2025-06-20)

- _posts/en/newsletters/2025-07-11-newsletter.md
- _topics/en/acc.md
- _topics/en/async-payments.md
- _topics/en/onion-messages.md
- _topics/en/op_cat.md
- _topics/en/op_checksigfromstack.md
- _topics/en/op_checktemplateverify.md
- _topics/en/output-script-descriptors.md
- _topics/en/ptlc.md
- _topics/en/quantum-resistance.md
- _topics/en/vaults.md
> Newsletter: add 362 (2025-07-11)

- _posts/en/newsletters/2025-08-01-newsletter.md
Having a link in the first line turns the bullet point into an anchor which is not expected here. Shifting the link to BIP360 to the next line removes the anchor.
> Fix unintended anchor creation in Newsletter #365
