bitcoinops/bitcoinops.github.io

index.md
Addresses the following point from #1:
> "No business model, profit motive, etc." What language can we use to speak to this? It is a common question about us so would be good to proactively address it.
=> Clarify business model

_data/associates.yml, _data/sponsors.yml, _posts/en/newsletters/2018-07-17-newsletter.md
=> Minor edits

_layouts/home.html, _posts/en/2018-07-20-announcing-bitcoin-optech.md, index.md
Publish the "announcing bitcoin optech" blog post
=> Launch blog

_includes/members.html
I think this looks cleaner. Thoughts?
=> reduce whitespace with company logos

_layouts/newsletter.html, _layouts/post.html, _posts/en/2018-07-20-announcing-bitcoin-optech.md, assets/css/main.scss, assets/css/post.css
- Centers titles and date
- adds date to newsletter posts
- adds space between the horizontal bar and text
blog post before:
blog post after:
newsletter before:
newsletter after:
=> Style changes

workshops.md
Adds early announcement for workshop #2 in Paris and tidies up the page.
Closes #39
=> Update workshop page

_posts/en/2018-09-04-dashboard-announcement.md
Changes date on dashboard announcement blog post from Aug 30 -> Sept 4.
=> Fix date of dashboard announcement post

_posts/en/newsletters/2018-09-11-newsletter.md
Should have been added before merging #65
=> Newsletters: Add workshop details and remove TODO

_posts/en/newsletters/2018-10-16-newsletter.md
Slow news/commit week, so it's still mostly summaries of talks from last week's Dev++ and this week's CoreDev.tech, although I've put it into our regular format.
Two notes:
1. @kanzure has been transcribing his talks from Dev++ after the fact, probably based on the videos, and so I was able to link to the transcript for one of the talks I highlight.  For the other talk from him I highlighted, I don't see a transcript; however it might be a good idea to check the [recent changes page](http://diyhpl.us/wiki/recentchanges/) on his site to see if it gets transcribed in the next 24 hours prior to this newsletter being merged.
2. For CoreDev.tech, two transcripts I thought we're potentially worth mentioning but didn't were Gleb's talk about tx relay reconciliation and kallewoof's BIP322, but …
=> Newsletters: add #17 (2018-10-16)

workshops.md
I think this is the right level of detail. Attendees have all the logistics information in emails.
Closes #73
=> Workshops: Add Paris workshop

_includes/header.html
=> Layout: add link to dashboard in header

_data/associates.yml
=> added schmidty to associates

_includes/references.md, _posts/en/newsletters/2018-12-18-newsletter.md
Comments/criticism appreciated on the opinions expressed in the user-organized-withdrawals news item (and everywhere else too, of course).
=> Newsletters: add #26 (2018-12-18)

_posts/en/newsletters/2018-11-20-newsletter.md, _posts/en/newsletters/2019-01-08-newsletter.md, _posts/en/newsletters/2019-01-22-newsletter.md
A short newsletter this week due to a lack of news (but with plenty of interesting merges).  While scanning merges, I noticed that C-Lightning changed the name of a file we had previously linked to, so this PR also updates those links.
=> Newsletters: add #30 (2019-01-22)

_includes/references.md, _posts/en/newsletters/2018-12-28-newsletter.md, _posts/en/newsletters/2019-01-29-newsletter.md
Slow news week, so I let it the summaries be a bit longer than normal.  Please feel free to complain.  :-)
=> Newsletters: add #31 (2019-01-29)

_includes/references.md, _posts/en/newsletters/2019-02-05-newsletter.md
=> Newsletters: add #32 (2019-02-05)

_includes/linkers/issues.md, _includes/references.md, _posts/en/newsletters/2019-02-19-newsletter.md
Long!  (Somebody remind me to schedule a vacation for the next time a Bitcoin Core feature freeze is planned!  :-)
=> Newsletters: add #34 (2019-02-19)

_posts/en/newsletters/2019-03-05-newsletter.md
=> Newsletters: add #36 (2019-03-05)

_posts/en/newsletters/2019-03-05-newsletter.md
Thanks for reporting @sipa and @roconnor!
=> Newsletter #36: fix sighash error

404.html
changed layout for 404 page to be consistent with rest of the site
=> 404 Page Layout to use standard page layout

_posts/en/newsletters/2019-03-12-newsletter.md
Mentioned by @rustyrussell here: https://twitter.com/rusty_twit/status/1105610129934700544
(Sorry!  And, wow, thanks for the amazing compliment!)
=> Newsletter #37: s/removes/deprecates/ C-Lightning newaddr "address" field

_posts/en/newsletters/2019-03-19-newsletter.md
Suggested by @xekyo https://twitter.com/murchandamus/status/1108048276018749441
=> Newsletter #38: add note about bech32 fee estimation

_includes/references.md, _posts/en/newsletters/2019-05-21-newsletter.md
Regular length this week.
CC: @ajtowns (section about bip-anyprevout)
=> Newsletters: add news47 (2019-05-21)

_includes/specials/bech32/14-security.md, _posts/en/newsletters/2019-06-19-newsletter.md
=> Newsletters: add 51 (2019-06-19)

_includes/specials/bech32/16-checklist.md, _posts/en/2019-03-19-bech32-sending-support.md, _posts/en/newsletters/2019-07-03-newsletter.md
=> Newsletters: add 53 (2019-07-03)

STYLE.md
Closes #165 
This is all I can think of for the moment.  I assume that we'll add to it in subsequent weeks.
=> Docs: add style guide

STYLE.md
I wanted to throw in a few from my list.
A couple I was not sure about:
- P2SH-P2WSH (is this it or P2SH-wrapped P2WPKH or I have seen "nested" as well)
- P2SH-P2WPKH
=> Style additions

_includes/specials/bech32/21-brd.md
=> News58: Typo: s/P2WPKH/P2PKH/

_includes/references.md, _includes/specials/bech32/23-compat.md, _posts/en/2019-03-19-bech32-sending-support.md, _posts/en/newsletters/2019-08-21-newsletter.md
=> Newsletters: add 60 (2019-08-21)

_posts/en/newsletters/2019-09-18-newsletter.md
Remove NODE_ prefix from network services in RPC response
=> Fix NODE_ prefix in 2019-09-18-newsletter.md

_posts/en/newsletters/2019-09-11-newsletter.md
=> newsletter 63: small correction to TxProbe description

_posts/en/newsletters/2019-02-19-newsletter.md, _posts/en/newsletters/2019-10-02-newsletter.md, _posts/en/newsletters/2019-10-09-newsletter.md
- ~~[ ] The paragraph starting "We at Optech are saddened to hear these sentiments" is meant to be presented as an Optech group opinion, so please mention if you don't think it accurately reflects your thinking about building on schnorr and taproot, or you think it's otherwise inappropriate for the newsletter.~~  Edit: removed
=> Newsletters: add 67 (2019-10-09)

STYLE.md
=> October 2019 style guide updates

_topics/en/channel-factories.md, _topics/en/hold-invoices.md, _topics/en/jit-routing.md, _topics/en/multipath-payments.md, _topics/en/splicing.md, _topics/en/spontaneous-payments.md, _topics/en/trampoline-payments.md, _topics/en/watchtowers.md
Eight proposed pages for the new `/en/topics/` section of the site.  Suggested reviewer is @adamjonas
=> Topics: add new topics (adamjonas)

_includes/references.md, _topics/en/bech32.md, _topics/en/block-explorers.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/covenants.md, _topics/en/dandelion.md, _topics/en/sidechains.md, _topics/en/signet.md, _topics/en/utreexo.md
Eight proposed pages for the new `/en/topics/` section of the site.  Suggested reviewer is @bitschmidty  
Note: tests expected to fail on the final "production" test because of the FIXME link pointing to a topic that's part of a different PR.  That's the last test we run, so if it's the only failure, this should be ok.
=> Topics: add new topics (bitschmidty)

_posts/en/newsletters/2019-11-13-newsletter.md
Found a spell error during JP translation. I know this is already published so just FYI (doesn't have to be incorporated).
=> spell error

_includes/references.md, _posts/en/newsletters/2019-11-20-newsletter.md
=> Newsletters: add 73 (2019-11-20)

CONTRIBUTING.md
Closes https://github.com/bitcoinops/bitcoinops.github.io/issues/276
=> add CONTRIBUTING guide for translations

_includes/references.md, _posts/en/newsletters/2019-11-27-newsletter.md, _topics/en/multipath-payments.md
Note, I may be unavailable to make updates after Tuesday 20:00 UTC, as I'll be traveling.  As always, feel free to push edits as necessary.
=> Newsletters: add 74 (2019-11-27)

_posts/en/newsletters/2019-12-11-newsletter.md
=> Newsletters: add 76 (2019-12-11)

_topics/en/psbt.md
See https://github.com/bitcoinops/bitcoinops.github.io/issues/171#issuecomment-528007027 and https://github.com/bitcoinops/bitcoinops.github.io/pull/219#discussion_r320321053
=> Change 'partially-signed' to 'partially signed' in topic page

STYLE.md, _posts/en/newsletters/2020-01-22-newsletter.md
=> Newsletters: add 81 (2020-01-22)

_includes/references.md, _posts/en/newsletters/2020-01-29-newsletter.md
=> Newsletters: add 82 (2020-01-29)

_config.yml
Closes #350 
Small change to prevent double slashes '//' in RSS feed related urls.
=> Config base url change to correct rss feed urls.

_data/associates.yml, _posts/en/newsletters/2019-05-29-newsletter.md, about.md
- Mike's bio
- About page spelling change
=> Associates updates

_includes/references.md, _posts/en/newsletters/2020-02-26-newsletter.md
=> Newsletters: add 86 (2020-02-26)

_posts/en/newsletters/2020-03-04-newsletter.md
=> Newsletters: add #87 (2020-03-04)

_includes/references.md, _posts/en/newsletters/2020-03-11-newsletter.md, assets/css/main.scss
Closes #365 
Short one this week; guess everyone was prepping for either the MIT conference or the virus (or both).
=> Newsletters: add 88 (2020-03-11)

_includes/references.md, _posts/en/newsletters/2020-04-01-newsletter.md
=> Newsletters: add 91 (2020-04-01)

_posts/en/newsletters/2020-03-11-newsletter.md, _posts/en/newsletters/2020-04-08-newsletter.md
=> Newsletters: add 92 (2020-04-08)

STYLE.md, _includes/linkers/issues.md, _includes/references.md, _posts/en/newsletters/2020-04-22-newsletter.md
=> Newsletters: add 94 (2020-04-22)

_topics/en/anchor-outputs.md, _topics/en/coinjoin.md, _topics/en/covenants.md, _topics/en/eclipse-attacks.md, _topics/en/eltoo.md, _topics/en/generic-signmessage.md, _topics/en/hold-invoices.md, _topics/en/hwi.md, _topics/en/mast.md, _topics/en/miniscript.md, _topics/en/multipath-payments.md, _topics/en/output-script-descriptors.md, _topics/en/payjoin.md, _topics/en/psbt.md, _topics/en/replace-by-fee.md, _topics/en/reproducible-builds.md, _topics/en/schnorr-signatures.md, _topics/en/sighash_noinput.md, _topics/en/spontaneous-payments.md, _topics/en/taproot.md, _topics/en/tapscript.md, _topics/en/watchtowers.md, en/topic-dates.md
This just adds mentions to the index.  No additional entries are added (I'm working on catching that up separately).
=> Topics: update with mentions from January to April 2020

_topics/en/large-channels.md
=> New topic: large channels

_posts/en/newsletters/2020-06-17-newsletter.md
=> Newsletters: add 102 (2020-06-17)

_posts/en/newsletters/2020-06-17-newsletter.md
Based on [this correction request](https://twitter.com/mHaGqnOACyFm0h5/status/1273333941433483265) and [review](https://twitter.com/mHaGqnOACyFm0h5/status/1273343003642531850) by @nothingmuch 
If anyone's curious, here's the relevant section of the paper:
=> News102: correct output commitment text in WabiSabi

_topics/en/anchor-outputs.md, _topics/en/coinjoin.md, _topics/en/compact-block-filters.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/cpfp.md, _topics/en/eclipse-attacks.md, _topics/en/generic-signmessage.md, _topics/en/large-channels.md, _topics/en/multipath-payments.md, _topics/en/output-script-descriptors.md, _topics/en/psbt.md, _topics/en/schnorr-signatures.md, _topics/en/signet.md, _topics/en/spontaneous-payments.md, _topics/en/taproot.md, _topics/en/watchtowers.md
Just links to topic mentions made in May, not any new topics.
=> Topics: topic updates for June

_posts/en/newsletters/2020-07-01-newsletter.md
@michaelfolkson I made edits to your transcripts section; please let me know if you see any problems and I'll revert the changes or make further edits.  Thanks for writing and transcribing!
=> Newsletters: add 104 (2020-07-01)

_posts/en/newsletters/2020-07-01-newsletter.md
Reported by @kanzure (thanks!)
=> News104: fix typo

STYLE.md, _includes/linkers/issues.md, _posts/en/newsletters/2020-07-08-newsletter.md
=> Newsletters: add 105 (2020-07-08)

STYLE.md
Various items noticed while reviewing; open for discussion.
=> WIP: style guide updates

_posts/en/newsletters/2020-07-15-newsletter.md
=> Newsletters: add 106 (2020-07-15)

_posts/en/newsletters/2020-07-22-newsletter.md
=> Newsletters: add 107 (2020-07-22)

_posts/en/newsletters/2020-07-22-newsletter.md
This PR was motivated by seeing a missing period when reading today's newsletter, then added a few very optional suggestions.
=> news107 touch-ups

_topics/en/multipath-payments.md
Add a link to item mentioning the c-lightning PR to the list of mentions.
=> Mention c-lightning adding multipath payments

_posts/en/newsletters/2020-08-05-newsletter.md
=> Newsletters: add 109 (2020-08-05)

Makefile, _posts/en/2019-02-11-rbf-in-the-wild.md, _posts/en/2019-11-12-topics-announcement.md, _posts/en/newsletters/2018-08-14-newsletter.md, _posts/en/newsletters/2018-09-04-newsletter.md, _posts/en/newsletters/2018-10-30-newsletter.md, _posts/en/newsletters/2019-02-05-newsletter.md, _posts/en/newsletters/2019-04-23-newsletter.md, _posts/en/newsletters/2019-05-14-newsletter.md, _posts/en/newsletters/2019-06-12-newsletter.md, _posts/en/newsletters/2019-06-19-newsletter.md, _posts/en/newsletters/2020-04-08-newsletter.md, _topics/en/op_checksigfromstack.md, en/scaling/fee-bumping/index.md
I appear to to have a a problem typing the the same word twice.  @adamjonas has has been catching most of of these, but but hopefully this this test will allow me to to address my own failings.
Test produced one false positive on on our existing documents, which I addressed with with a small rewrite.
=> Test: duplicate words check (with fixes for existing duplicates)

_posts/en/newsletters/2020-08-05-newsletter.md
Thanks to @pinheadmz for reporting!
=> News109: signets use proof of work

_includes/articles/veriphi-segwit-batching.md, _posts/en/2020-08-12-veriphi-segwit-batching.md, _posts/en/newsletters/2020-08-12-newsletter.md
=> Newsletters: add 110 (2020-08-12)

_posts/en/newsletters/2020-08-19-newsletter.md
Happy eleventy-first newsletter!
=> Newsletters: add #111 (2020-08-19)

_topics/en/adaptor-signatures.md
Don't let the confident tone of this text fool you---it's author still feels he has a very poor understanding of adaptor sigs.  I've tried to make my description as easy to prove wrong as possible (while also hopefully keeping it readable by non-experts), but please don't assume that its detail and assertiveness are proxies for correctness.
=> Topics: add adaptor signatures

_posts/en/newsletters/2020-08-26-newsletter.md
=> Newsletters: add 112 (2020-08-26)

_posts/en/newsletters/2020-09-09-newsletter.md
=> Newsletters: add 114 (2020-09-09)

_posts/en/newsletters/2020-09-23-newsletter.md
=> Newsletters: add 116 (2020-09-23)

_topics/en/addr-v2.md, _topics/en/anchor-outputs.md, _topics/en/compact-block-filters.md, _topics/en/covenants.md, _topics/en/eltoo.md, _topics/en/large-channels.md, _topics/en/mast.md, _topics/en/miniscript.md, _topics/en/multipath-payments.md, _topics/en/op_checktemplateverify.md, _topics/en/package-relay.md, _topics/en/payjoin.md, _topics/en/psbt.md, _topics/en/schnorr-signatures.md, _topics/en/sighash_noinput.md, _topics/en/signet.md, _topics/en/taproot.md, _topics/en/transaction-pinning.md
=> Topics: update with mentions from August 2020

_topics/en/adaptor-signatures.md, _topics/en/htlc.md, _topics/en/ptlc.md
(We normally do one topic at a time now, but these were related so I did them together).
=> Topics: add HTLCs and PTLCs

_posts/en/newsletters/2020-09-30-newsletter.md
=> Newsletters: add 117 (2020-09-30)

_topics/en/adaptor-signatures.md, _topics/en/addr-v2.md, _topics/en/anchor-outputs.md, _topics/en/eclipse-attacks.md, _topics/en/hwi.md, _topics/en/large-channels.md, _topics/en/miniscript.md, _topics/en/payjoin.md, _topics/en/psbt.md, _topics/en/ptlc.md, _topics/en/replace-by-fee.md, _topics/en/schnorr-signatures.md, _topics/en/signet.md, _topics/en/taproot.md, _topics/en/transaction-pinning.md
See [this comment](https://github.com/bitcoinops/bitcoinops.github.io/pull/460#pullrequestreview-494504105) for suggestions about how to review this PR.
=> Topics: update for mentions from September

_posts/en/newsletters/2020-10-07-newsletter.md
=> Newsletters: add 118 (2020-10-07)

_topics/en/generic-signmessage.md, _topics/en/psbt.md
This adds the entries from the newsletter published today.  Going forward, I plan to make topic updates in the primary PR for each newsletter.
=> Topics: add new entries from Newsletter 118

CONTRIBUTING.md
Add tip about reviewing topic page updates.
=> Update CONTRIBUTING.md with review tips

_posts/en/newsletters/2020-10-21-newsletter.md, _topics/en/musig.md, _topics/en/payjoin.md, _topics/en/schnorr-signatures.md, _topics/en/taproot.md, _topics/en/tapscript.md
Note: I'll be unavailable to make further edits after about Tuesday 14:00 U.S. eastern (16:00 UTC), including being unavailable for last-minute edits Wednesday morning.
=> Newsletters: add 120 (2020-10-21)

_posts/en/newsletters/2020-10-28-newsletter.md, _topics/en/generic-signmessage.md, _topics/en/htlc.md, _topics/en/mast.md
=> Newsletters: add 121 (2020-10-28)

_posts/en/newsletters/2020-11-11-newsletter.md, _topics/en/assumeutxo.md, _topics/en/eclipse-attacks.md
Happy Armistice Day.  Unrelated: a short newsletter this week.
=> Newsletters: add 123 (2020-11-11)

_posts/en/newsletters/2020-11-18-newsletter.md, _topics/en/multipath-payments.md, _topics/en/output-script-descriptors.md, _topics/en/payjoin.md
=> Newsletters: add 124 (2020-11-18)

_posts/en/newsletters/2020-12-02-newsletter.md, _topics/en/miniscript.md, en/topic-dates.md
=> Newsletters: add 126 (2020-12-02)

_posts/en/newsletters/2020-10-07-newsletter.md
Contains the commit from #495 by @MarcoFalke
=> News118: add correction to unknown message item

_topics/en/eclipse-attacks.md
Fixes a problem on https://bitcoinops.org/en/topics/eclipse-attacks/
=> Typo: make YAML data a string literal

_includes/linkers/issues.md, _includes/references.md, _posts/en/newsletters/2021-01-06-newsletter.md
=> Newsletters: add 130 (2021-01-06)

_posts/en/newsletters/2021-01-13-newsletter.md, _topics/en/assumeutxo.md, _topics/en/bech32.md, _topics/en/eclipse-attacks.md
Note: this PR adds an old topic entry to eclipse attacks, which were described in an entry but didn't explicitly say "eclipse" so I didn't notice it when creating the Eclipse Attack topic.  Relevant this week because we're linking to it.
=> Newsletters: add 131 (2020-01-13)

_includes/linkers/issues.md, _includes/references.md, _posts/en/newsletters/2021-01-20-newsletter.md, _topics/en/addr-v2.md, _topics/en/compact-block-filters.md, _topics/en/output-script-descriptors.md, _topics/en/payjoin.md, _topics/en/signet.md, _topics/en/vaults.md
=> Newsletters: add 132 (2021-01-20)

_posts/en/newsletters/2021-01-27-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/compact-block-filters.md, _topics/en/psbt.md, _topics/en/replace-by-fee.md, _topics/en/reproducible-builds.md, _topics/en/taproot.md
=> Newsletters: add 133 (2021-01-27)

_posts/en/newsletters/2021-02-24-newsletter.md, _topics/en/compact-block-filters.md, _topics/en/output-script-descriptors.md, _topics/en/schnorr-signatures.md, _topics/en/taproot.md
=> Newsletters: add 137 (2021-02-24)

_posts/en/newsletters/2021-03-03-newsletter.md
See https://github.com/bitcoinops/bitcoinops.github.io/pull/523#discussion_r586596928
=> News138: Rust-Bitcoin -> Rust Bitcoin

_posts/ja/newsletters/2021-03-03-newsletter.md
After #521 is merged, the link(`[news137 taproot activation]`) can be updated.
=> Newsletter-138:Translate into Japanese

_posts/en/newsletters/2021-03-10-newsletter.md
Addresses the remaining review feedback of #526 and adds some additional edits.
=> News139 post-op edits

_posts/en/newsletters/2021-03-17-newsletter.md, _topics/en/replace-by-fee.md, _topics/en/spontaneous-payments.md
=> Newsletters: add 140 (2021-03-17)

STYLE.md
Some proposed suggestions, open to feedback / corrections / improvements!
=> Style guide additions

_posts/en/newsletters/2021-03-24-newsletter.md, _topics/en/bech32.md, _topics/en/output-linking.md, _topics/en/output-script-descriptors.md, _topics/en/psbt.md, _topics/en/taproot.md, _topics/en/tapscript.md
=> Newsletters: add 141 (2021-03-24)

_posts/en/newsletters/2021-03-24-newsletter.md
Per feedback from https://github.com/bitcoinops/bitcoinops.github.io/pull/533#pullrequestreview-619682192
=> News141: additions

_posts/ja/newsletters/2021-03-24-newsletter.md
I will update the `[news140 recovery]` link after the merge of #530.
=> Newsletter-141:Translate into Japanese

_topics/en/dual-funding.md
=> New topic: dual funding

_includes/references.md, _topics/en/payment-batching.md
Short and simple since we already have an article about it, which this topic links prominently.
=> New topic: payment batching

_posts/en/newsletters/2021-03-31-newsletter.md, _topics/en/htlc.md, _topics/en/jit-routing.md, _topics/en/multipath-payments.md
=> Newsletters: add 142 (2021-03-27)

_topics/en/anchor-outputs.md
Noticed this after tweeting to consult this topic!
https://twitter.com/jonatack/status/1379839115676561408
=> topics: anchor outputs fixup

_topics/en/multisignature.md
Note: doesn't include any significant description of threshold signatures because I plan to create a separate topic for that.  For the same reason, it doesn't describe signature aggregation, although I'm not sure we have enough mentions to warrant a topic on that yet.
=> New topic: multisignature

_posts/en/newsletters/2021-04-14-newsletter.md, _topics/en/multipath-payments.md, _topics/en/signet.md, _topics/en/soft-fork-activation.md, _topics/en/spontaneous-payments.md, _topics/en/taproot.md
=> Newsletters: add 144 (2021-04-14)

_posts/en/newsletters/2021-04-21-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/cpfp.md, _topics/en/miniscript.md, _topics/en/offers.md, _topics/en/op_checktemplateverify.md, _topics/en/output-script-descriptors.md, _topics/en/payjoin.md, _topics/en/soft-fork-activation.md, _topics/en/taproot.md
=> Newsletters: add 145 (2021-04-21)

_posts/en/newsletters/2021-05-05-newsletter.md, _topics/en/assumeutxo.md, _topics/en/multipath-payments.md, _topics/en/soft-fork-activation.md, _topics/en/taproot.md
=> Newsletters: add 147 (2021-05-05)

_includes/functions/details-list.md, _posts/en/newsletters/2021-05-12-newsletter.md, _topics/en/dual-funding.md, _topics/en/output-script-descriptors.md, _topics/en/replace-by-fee.md, _topics/en/schnorr-signatures.md, _topics/en/taproot.md, _topics/en/transaction-pinning.md
=> Newsletters: add 148 (2021-05-12)

_posts/en/newsletters/2021-05-19-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/bech32.md, _topics/en/cpfp.md, _topics/en/multipath-payments.md, _topics/en/psbt.md, _topics/en/replace-by-fee.md, _topics/en/reproducible-builds.md, _topics/en/trampoline-payments.md
=> Newsletters: add 149 (2021-05-19)

_posts/en/newsletters/2021-05-26-newsletter.md, _topics/en/output-script-descriptors.md
=> Newsletters: add 150 (2021-05-26)

_posts/en/newsletters/2021-06-02-newsletter.md, _topics/en/coinjoin.md, _topics/en/cpfp.md, _topics/en/package-relay.md, _topics/en/payment-batching.md, _topics/en/signet.md
=> Newsletters: add 151 (2021-06-02)

Makefile, _contrib/new-topic, _data/schemas/topics.yaml, _includes/snippets/msig-terms.md, _topics/en/multisignature.md, _topics/en/threshold-signature.md
Includes an unrelated update to the `new-topic` script that I realized would be nice since I'm using it for the first time since #551.  I can split that off into a separate PR if anyone cares.
=> New topic: threshold signature

_posts/en/newsletters/2021-06-09-newsletter.md, _topics/en/anonymity-networks.md, _topics/en/multipath-payments.md, _topics/en/output-script-descriptors.md, _topics/en/taproot.md
=> Newsletters: add 152 (2021-06-09)

STYLE.md, _config.yml, _includes/specials/taproot/00-bech32m.md, _posts/en/newsletters/2021-06-23-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/bech32.md, _topics/en/multipath-payments.md, _topics/en/payjoin.md, _topics/en/replace-by-fee.md, _topics/en/taproot.md, _topics/en/tapscript.md
Note: adds some entries to the style guide; let me know if any y'all object.
=> Newsletters: add 154 (2021-06-23)

_posts/en/newsletters/2021-06-23-newsletter.md, _topics/en/bech32.md
Spotted by Adam Gibson / @AdamISZ.
=> News154: fix Bech32m header

_includes/specials/taproot/en/01-single-sig.md, _posts/en/newsletters/2021-06-30-newsletter.md, _topics/en/adaptor-signatures.md, _topics/en/large-channels.md, _topics/en/musig.md, _topics/en/psbt.md, _topics/en/taproot.md, en/tools/calc-size.md
=> Newsletters: add 155 (2021-06-30)

_posts/en/newsletters/2021-07-14-newsletter.md
=> News157: Fix typo

STYLE.md, _includes/specials/taproot/en/04-why-wait.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-07-21-newsletter.md, _topics/en/anonymity-networks.md, _topics/en/bech32.md, _topics/en/discreet-log-contracts.md, _topics/en/taproot.md, _topics/en/unannounced-channels.md
Note: adds an entry to the style guide.  As always, let me know if anyone disagrees and I'll move that to a separate PR (or realize it's dumb and just delete it).
=> Newsletters: add 158 (2021-07-21)

_topics/en/cpfp-carve-out.md, _topics/en/cpfp.md
Motivation: https://github.com/bitcoinops/bitcoinops.github.io/pull/572#discussion_r635159250 
and https://github.com/bitcoinops/bitcoinops.github.io/blob/master/STYLE.md 
I decided to change the topics and leave newsletters as it seems to be our approach to avoid newsletter updates except for more drastic corrections.
=> Topics: CPFP remove hyphens

_includes/specials/taproot/en/06-multisignatures.md
As with the other rare occasions where we've made a significant post-publication edit, I'll add a Corrections section to next week's newsletter linking back here.
=> News160: update MuSig2 description

_includes/specials/taproot/en/06-multisignatures.md
`working on`
---
This is an amazing special, thanks a bunch! 
Sorry for not catching this earlier pre-publishing.
=> [newsletters/2021/08/04/] grammer nit missing word 

_includes/specials/taproot/en/07-nonces.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-08-11-newsletter.md, _topics/en/coinjoin.md, _topics/en/dual-funding.md, _topics/en/multisignature.md, _topics/en/musig.md, _topics/en/offers.md
I'm terribly behind this weekend, so I'll have to fill this in on Monday like everyone else.  Sorry!
=> Newsletters: add 161 (2021-08-11)

_data/compatibility/bitgo.yaml, _includes/specials/taproot/en/08-signature-adaptors.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-08-18-newsletter.md, _topics/en/adaptor-signatures.md, _topics/en/offers.md, _topics/en/output-linking.md, _topics/en/package-relay.md, _topics/en/reproducible-builds.md, _topics/en/uneconomical-outputs.md
=> Newsletters: add 162 (2021-08-18)

_posts/ja/newsletters/2021-09-08-newsletter.md
This is an additional typo fix for #640.
=> Fix typo PBST -> PSBT

_includes/specials/taproot/en/12-backups.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-09-08-newsletter.md, _posts/en/newsletters/2021-09-15-newsletter.md, _topics/en/anonymity-networks.md, _topics/en/covenants.md, _topics/en/signet.md, _topics/en/taproot.md, _topics/en/vaults.md
Also thanks to @rustyrussell for noting the inaccuracy in our description of `BOLTs #843` last week; a clarification is added to this newsletter.
=> Newsletters: add 2021-09-15

_includes/specials/taproot/en/13-signet.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-09-22-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/cpfp.md, _topics/en/package-relay.md, _topics/en/replace-by-fee.md, _topics/en/signet.md, _topics/en/taproot.md, _topics/en/transaction-bloom-filtering.md
=> Newsletters: add 167 (2021-09-22)

_includes/specials/taproot/en/14-signmessage.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-09-29-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/discreet-log-contracts.md, _topics/en/generic-signmessage.md, _topics/en/hd-key-generation.md
=> Newsletters: add 168 (2021-09-29)

_posts/en/newsletters/2019-03-12-newsletter.md, _posts/en/newsletters/2019-05-29-newsletter.md, _posts/en/newsletters/2020-01-08-newsletter.md, _posts/en/newsletters/2020-09-16-newsletter.md, _posts/en/newsletters/2020-09-23-newsletter.md, _posts/ja/newsletters/2020-01-08-newsletter-ja.md
See https://github.com/bitcoinops/scaling-book/pull/30
=> Remove links to https://github.com/bitcoinops/scaling-book/blob/master/x.payment_batching/payment_batching.md

_includes/specials/taproot/en/17-keypath-universality.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-10-13-newsletter.md, _topics/en/eltoo.md, _topics/en/psbt.md, _topics/en/ptlc.md, _topics/en/taproot.md, _topics/en/uneconomical-outputs.md, _topics/en/vaults.md
Note, I wrote this one in a bit of a rush and it probably has more problems than usual.  Sorry about that, and please don't feel bad if you have lots of criticism.  I'll make time to address all issues.
=> Newsletters: add 170 (2021-10-13)

STYLE.md, _includes/specials/taproot/en/20-activation.md, _posts/en/newsletters/2021-11-03-newsletter.md, _topics/en/atomic-multipath.md, _topics/en/spontaneous-payments.md, _topics/en/taproot.md
=> Newsletters: add 173 (2021-11-03)

STYLE.md, _includes/specials/taproot/en/21-thanks.md, _posts/en/2021-06-23-preparing-for-taproot.md, _posts/en/newsletters/2021-11-10-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/compact-block-filters.md, _topics/en/discreet-log-contracts.md, _topics/en/eltoo.md, _topics/en/musig.md, _topics/en/offers.md, _topics/en/op_checktemplateverify.md, _topics/en/ptlc.md, _topics/en/trampoline-payments.md
=> Newsletters: add 174 (2021-11-10)

STYLE.md
Just want to correct the capitalization in vB of the recent style guide update.
=> Style: Fix typo in sat/vB

_posts/en/newsletters/2021-11-17-newsletter.md, _topics/en/anonymity-networks.md, _topics/en/bech32.md, _topics/en/onion-messages.md, _topics/en/taproot.md
=> Newsletters: add 175 (2021-11-17)

_posts/en/newsletters/2021-11-24-newsletter.md, _topics/en/atomic-multipath.md, _topics/en/eclipse-attacks.md
=> Newsletters: add 176 (2021-11-24)

_posts/en/newsletters/2022-01-12-newsletter.md, _topics/en/erlay.md, _topics/en/offers.md, _topics/en/onion-messages.md, _topics/en/stateless-invoices.md
=> Newsletters: add 182 (2021-01-12)

_includes/linkers/issues.md, _includes/references.md, _posts/en/newsletters/2022-01-19-newsletter.md, _topics/en/op_checktemplateverify.md, _topics/en/psbt.md, _topics/en/stateless-invoices.md
=> Newsletters: add 183 (2022-01-19)

_posts/en/newsletters/2022-01-26-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/covenants.md, _topics/en/onion-messages.md, _topics/en/pay-to-contract-outputs.md, _topics/en/psbt.md, _topics/en/taproot.md
=> Newsletters: add 184 (2022-01-26)

_includes/references.md, _posts/en/newsletters/2022-02-02-newsletter.md, _topics/en/discreet-log-contracts.md, _topics/en/joinpools.md, _topics/en/op_checktemplateverify.md, _topics/en/sighash_anyprevout.md
=> Newsletters: add 185 (2022-02-02)

_posts/en/newsletters/2022-02-16-newsletter.md, _topics/en/covenants.md, _topics/en/generic-signmessage.md, _topics/en/op_checksigfromstack.md
- Client/services section @bitschmidty 
- Eclair 2164 @dongcarl 
- Other stuff @harding 
(Sorry, there are probably problems with this PR.  My laptop broke and I haven't yet restored my ability to preview the newsletter locally.)
=> Newsletters: add 187 (2022-02-16)

_posts/en/newsletters/2022-03-09-newsletter.md, _topics/en/covenants.md, _topics/en/cve.md, _topics/en/onion-messages.md, _topics/en/sidechains.md
=> Newsletters: add 190 (2022-03-09)

_posts/en/newsletters/2022-03-16-newsletter.md, _topics/en/fee-sniping.md, _topics/en/op_checktemplateverify.md, _topics/en/output-script-descriptors.md, _topics/en/replace-by-fee.md, _topics/en/simplicity.md, _topics/en/transaction-pinning.md, _topics/en/vaults.md
=> Newsletters: add 191 (2022-03-16)

_posts/en/newsletters/2022-03-23-newsletter.md, _topics/en/coinswap.md, _topics/en/soft-fork-activation.md
=> Newsletters: add 192 (2022-03-23)

_posts/en/newsletters/2022-03-30-newsletter.md, _topics/en/musig.md, _topics/en/replace-by-fee.md
=> Newsletters: add 193 (2022-03-30)

_posts/en/newsletters/2022-03-30-newsletter.md
The link for Laolu's response to Rusty and the link for his minor update proposal are inverted.
=> Reverse osuntokun gossip links

_posts/en/newsletters/2022-04-06-newsletter.md, _topics/en/channel-commitment-upgrades.md, _topics/en/coinjoin.md, _topics/en/low-r-grinding.md, _topics/en/output-linking.md, _topics/en/payjoin.md, _topics/en/taproot.md
=> Newsletters: add 194 (2022-04-06)

_posts/en/newsletters/2022-04-20-newsletter.md, _topics/en/quantum-resistance.md, _topics/en/stateless-invoices.md
=> Newsletters: add 196 (2022-04-20)

_posts/en/newsletters/2022-04-27-newsletter.md
Re https://twitter.com/darosior/status/1519281847359975424
=> News197: clarify darosior's request

_posts/en/newsletters/2022-05-04-newsletter.md, _topics/en/large-channels.md, _topics/en/minisketch.md, _topics/en/musig.md, _topics/en/soft-fork-activation.md
=> Newsletters: add 198 (2022-05-04)

_posts/en/newsletters/2022-04-13-newsletter.md, _posts/ja/newsletters/2022-04-13-newsletter.md, _topics/en/stateless-invoices.md
Reported by Steve Myers (thanks!)
=> News195: fix PR # transposition error

_data/compatibility/bitmex.yaml
Circa early 2021
source: I deployed it
=> BitMEX issues p2wsh addresses only

_posts/en/newsletters/2022-05-11-newsletter.md
There's not really any news yet.  If I see anything easy in the next couple days, I'll add that, otherwise it'll be an easy newsletter.
=> Newsletters: add 199 (2022-05-11)

_posts/en/newsletters/2022-05-18-newsletter.md, _topics/en/covenants.md, _topics/en/eltoo.md, _topics/en/miniscript.md, _topics/en/op_checktemplateverify.md, _topics/en/output-script-descriptors.md, _topics/en/psbt.md, _topics/en/taproot.md, _topics/en/transaction-pinning.md
=> Newsletters: add 200 (2020-05-18)

_posts/cs/newsletters/2022-05-18-newsletter.md
Here is Czech translation of the 200th newsletter.
As becomes usual, I added footnotes explaining some terms since there are no topic translations. Additionally, I dared to add a link to a detailed Slovakian article (everybody who reads Czech can read Slovakian) explaining RGB. I hope it's OK, if not, please let me know.
=> Newsletter-200: Add Czech translation

_posts/en/newsletters/2022-05-25-newsletter.md, _topics/en/coin-selection.md, _topics/en/compact-block-relay.md, _topics/en/covenants.md, _topics/en/cpfp.md, _topics/en/package-relay.md, _topics/en/schnorr-signatures.md
=> Newsletters: add 201 (2022-05-25)

_data/contributors.yml, _includes/contributors.html, about.md, assets/css/main.scss
Opened as an alternative to https://github.com/bitcoinops/bitcoinops.github.io/pull/741
Proposed here: https://github.com/bitcoinops/bitcoinops.github.io/pull/741#issuecomment-1084773391
Preview of associated "about" page: https://deploy-preview-761--bitcoinops.netlify.app/about/
=> Contributors: add alum

_posts/en/newsletters/2022-06-01-newsletter.md, _topics/en/output-linking.md
(I'm sorry that all of the merge summaries this week are so trivial; I feel silly asking talented people to write obvious descriptions.)
=> Newsletters: add 202 (2022-06-01)

_posts/en/newsletters/2022-06-08-newsletter.md, _topics/en/miniscript.md, _topics/en/output-script-descriptors.md, _topics/en/zero-conf-channels.md
=> Newsletters: add 203 (2022-06-08)

_posts/en/newsletters/2022-06-15-newsletter.md, _topics/en/musig.md, _topics/en/package-relay.md, _topics/en/rendez-vous-routing.md, _topics/en/trampoline-payments.md
(Sorry for being a bit late this week.)
=> Newsletters: add 204 (2022-06-15)

_posts/en/newsletters/2022-06-22-newsletter.md, _topics/en/replace-by-fee.md
=> Newsletters: add 205 (2022-06-22)

_posts/en/newsletters/2022-06-29-newsletter.md, _topics/en/fee-sniping.md, _topics/en/multisignature.md, _topics/en/taproot.md
=> Newsletters: add 206 (2022-06-29)

_config.yml
closes https://github.com/bitcoinops/bitcoinops.github.io/issues/783
=> Social: add Mastodon

STYLE.md, _posts/en/newsletters/2022-07-13-newsletter.md, _topics/en/payment-probes.md
=> Newsletters: add 208 (2022-07-13)

_posts/en/newsletters/2022-07-20-newsletter.md, _topics/en/fee-sniping.md, _topics/en/miniscript.md, _topics/en/output-script-descriptors.md, _topics/en/schnorr-signatures.md
Sorry this isn't entirely done yet.  I ran out of time.  I'll try to get the lede, citations, and commit summaries in by the end of Monday.  (Also maybe do some editing.)
=> Newsletters: add 209 (2022-07-20)

_posts/en/newsletters/2022-07-27-newsletter.md, _topics/en/generic-signmessage.md, _topics/en/tapscript.md, _topics/en/uneconomical-outputs.md
=> Newsletters: add 210 (2022-07-27)

_config.yml, _posts/de/newsletters/2022-07-27-newsletter.md, _posts/zh/newsletters/2022-07-20-newsletter.md, de/blog.md, de/newsletters.md, de/publications.md
Initial setup to support German translations and translation of Newsletter 210.
=> Newsletter 210: Translate to German

_posts/en/newsletters/2022-08-03-newsletter.md, _topics/en/compact-block-relay.md, _topics/en/hd-key-generation.md, _topics/en/output-script-descriptors.md, _topics/en/rendez-vous-routing.md
I might add an additional News section item depending on how on list discussion goes in the next couple days.
=> Newsletters: add 211 (2022-08-03)

Makefile, _posts/en/newsletters/2022-08-10-newsletter.md, _topics/en/coin-selection.md, _topics/en/default-minimum-transaction-relay-feerates.md, _topics/en/replace-by-fee.md
=> Newsletters: add 212 (2022-08-10)

_posts/en/newsletters/2022-08-10-newsletter.md
There were a few outstanding review comments on yesterday's newsletter, but this one seems especially important to me because the currently published version seems confusing to me.
=> News212 follow-up: amend description of 25610

_posts/en/newsletters/2022-08-17-newsletter.md, _topics/en/discreet-log-contracts.md, _topics/en/dual-funding.md, _topics/en/output-script-descriptors.md, _topics/en/zero-conf-channels.md
=> Newsletters: add 213 (2022-08-17)

_posts/en/newsletters/2022-08-24-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/onion-messages.md, _topics/en/output-script-descriptors.md, _topics/en/silent-payments.md, _topics/en/splicing.md, _topics/en/static-channel-backups.md, _topics/en/zero-conf-channels.md
=> Newsletters: add 214 (2022-08-24)

_posts/en/newsletters/2022-08-31-newsletter.md, _topics/en/dual-funding.md, _topics/en/onion-messages.md, _topics/en/output-script-descriptors.md, _topics/en/schnorr-signatures.md, _topics/en/signet.md, _topics/en/zero-conf-channels.md
=> Newsletters: add 215 (2022-08-31)

_posts/ja/newsletters/2022-08-31-newsletter.md
This translation contains fix #846. Please point out if this fix is not necessary.
=> Newsletter-215:Translate into Japanese

_posts/de/newsletters/2022-08-24-newsletter.md
@Xekyo thanks in advance for the review.
=> Newsletter-214: Translate to German

_posts/en/newsletters/2022-09-07-newsletter.md, _topics/en/anonymity-networks.md, _topics/en/hwi.md, _topics/en/uneconomical-outputs.md
=> Newsletters: add 216 (2022-09-07)

_posts/ja/newsletters/2022-09-07-newsletter.md
This translation contains fix https://github.com/bitcoinops/bitcoinops.github.io/pull/853. Please point out if this fix is not necessary.
=> Newsletter-216:Translate into Japanese

_posts/de/newsletters/2022-08-31-newsletter.md
Thanks for the review, as always.
=> Newsletter-215: Translate to German

_posts/en/newsletters/2022-09-14-newsletter.md, _topics/en/dual-funding.md
=> Newsletters: add 217 (2022-09-14)

_posts/en/newsletters/2022-09-21-newsletter.md, _topics/en/compact-block-filters.md, _topics/en/offers.md, _topics/en/rendez-vous-routing.md, _topics/en/sidechains.md, _topics/en/sighash_anyprevout.md
=> Newsletters: add 218 (2022-09-21)

_posts/en/newsletters/2022-09-28-newsletter.md, _topics/en/op_checktemplateverify.md, _topics/en/sighash_anyprevout.md
=> Newsletters: add 219 (2022-09-28)

_posts/en/newsletters/2022-10-12-newsletter.md, _topics/en/block-explorers.md, _topics/en/output-linking.md
=> Newsletters: add 221 (2022-10-12)

_posts/fr/newsletters/2022-09-28-newsletter.md
[Update 2022-09-28-newsletter.md]
(https://github.com/Copinmalin/bitcoinops.github.io/commit/54ef28368aa6e96509f1b79f3de1c2ec13572efe)
Ready for review
=> Newsletter-219: Translate to French

_posts/fr/newsletters/2022-10-05-newsletter.md
Hello @jonatack and @bitschmidty,
You will find the translation of this newsletter 220,
Thanks for review and help,
=> Newsletter-220: Translate to French

_posts/en/newsletters/2022-10-12-newsletter.md
Fixes a missing term highlight in the english newsletter 221
=> (fix)newsletter 221: Highlighting fix

_posts/en/newsletters/2022-10-19-newsletter.md, _topics/en/addr-v2.md, _topics/en/block-explorers.md, _topics/en/compact-block-filters.md, _topics/en/cve.md, _topics/en/musig.md, _topics/en/replace-by-fee.md, _topics/en/sidechains.md, _topics/en/tapscript.md, _topics/en/utreexo.md, _topics/en/v2-p2p-transport.md
=> Newsletters: add 222 (2022-10-19)

_posts/en/newsletters/2022-10-19-newsletter.md
Error mentioned in https://twitter.com/lightcoin/status/1582711504994197505
Suggest waiting for @john-light to comment here or on Twitter that this is a reasonable correction before we merge.
=> News222: corrections to the rollups news item

_posts/en/newsletters/2022-10-26-newsletter.md
Of course I see this right after merging
=> News223: summary fixup

_posts/en/newsletters/2022-10-26-newsletter.md
Hope my correction is what was originally intended.
=> News223: Q&A item fixup

STYLE-DE.md
As mentioned in #832 by @Xekyo , it could make sense to have a language-specific list of terms. 
This PR introduces a language-specific style guide based on the structure of the [original guide](STYLES.md), and supplements it where necessary with rules for German translations.
Open TODOs:
@bitschmidty , @Xekyo , happy to get your input on this one.
=> Style guide for german translations

STYLE-DE.md, _posts/de/newsletters/2022-10-26-newsletter.md
Fixes review comments from @Xekyo and adds dual funding to german translation document.
=> German Newsletter 223 fixes

_posts/en/newsletters/2022-11-02-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/cpfp.md
Error [reported](https://twitter.com/realtbast/status/1587789414566137857) by @t-bast
=> News224: correction to presigned fee bumps news item

_posts/en/newsletters/2022-11-09-newsletter.md, _topics/en/cve.md, _topics/en/replace-by-fee.md, _topics/en/responsible-disclosures.md
=> Newsletters: add 225 (2022-11-09)

_posts/zh/newsletters/2022-10-19-newsletter.md
=> Newsletter-222: Chinese translation format fix

_posts/cs/newsletters/2022-05-18-newsletter.md, _posts/en/newsletters/2022-05-18-newsletter.md
Replaces incorrect `text` key with `title`. This broke my parser :neutral_face:.
=> Fix duplicate frontmatter key

_posts/en/newsletters/2022-11-16-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/covenants.md, _topics/en/multipath-payments.md
=> Newsletters: add 226 (2022-11-16)

_posts/cs/newsletters/2022-11-23-newsletter.md
Translation of #227 into Czech language.
I used to do Czech translations under account @nechteme but lost access to that account. So from now on, I will be submitting translations under this one.
=> Newsletter-227: Translate into Czech

_posts/en/newsletters/2022-11-30-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/offers.md, _topics/en/psbt.md
=> Newsletters: add 228 (2022-11-30)

STYLE-DE.md, _posts/de/newsletters/2022-11-02-newsletter.md
Also contains minor fixes to the German style guide.
=> Newsletter 224: Add german translation

_posts/en/newsletters/2022-12-07-newsletter.md
@bitschmidty I fixed Review Club anchor link in English post as well(https://github.com/bitcoinops/bitcoinops.github.io/pull/953#discussion_r1043462457).
=> Newsletter-229:Fix review club anchor link

_posts/cs/newsletters/2022-12-14-newsletter.md
Translation of no. 230 into Czech language.
=> Newsletter-230: Translate into Czech

_includes/references.md, _posts/en/newsletters/2022-12-21-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/dual-funding.md, _topics/en/fee-sponsorship.md, _topics/en/miniscript.md, _topics/en/musig.md, _topics/en/onion-messages.md, _topics/en/output-script-descriptors.md, _topics/en/package-relay.md, _topics/en/quantum-resistance.md, _topics/en/replace-by-fee.md, _topics/en/silent-payments.md, _topics/en/stateless-invoices.md, _topics/en/v2-p2p-transport.md, _topics/en/version-3-transaction-relay.md, _topics/en/zero-conf-channels.md
Thanks for early reviews from Mike and Mark, and thank you everyone for another great year of keeping our readers informed!
Whoops, just received some early reviews from Jon also while I was pushing this.  I'll be making those edits here.  Thanks Jon!
=> Newsletters: add 231 end-of-year special (2022-12-21)

_posts/en/newsletters/2023-01-04-newsletter.md, _topics/en/async-payments.md, _topics/en/hwi.md, _topics/en/offers.md, _topics/en/rendez-vous-routing.md, _topics/en/replace-by-fee.md
=> Newsletters: add 232 (2023-01-04)

_topics/en/taproot.md, _topics/en/transaction-pinning.md
Just found two typos, nothing more.
=> Nit: 2 typos

_posts/en/newsletters/2023-01-11-newsletter.md, _topics/en/async-payments.md
=> Newsletters: add 233 (2023-01-11)

_posts/en/newsletters/2023-01-11-newsletter.md
Caught during emailing the newsletter out
=> News233: summary fixup

_includes/references.md, _posts/en/newsletters/2023-01-18-newsletter.md, _topics/en/covenants.md, _topics/en/discreet-log-contracts.md, _topics/en/op_checktemplateverify.md, _topics/en/payment-batching.md, _topics/en/vaults.md
=> Newsletters: add 234 (2023-01-18)

_posts/en/newsletters/2023-01-25-newsletter.md, _topics/en/async-payments.md, _topics/en/ephemeral-anchors.md, _topics/en/signet.md
=> Newsletters: add 235 (2023-01-25)

_includes/references.md, _posts/en/newsletters/2023-02-01-newsletter.md, _topics/en/adaptor-signatures.md, _topics/en/anchor-outputs.md, _topics/en/async-payments.md, _topics/en/payjoin.md, _topics/en/ptlc.md, _topics/en/splicing.md, _topics/en/spontaneous-payments.md, _topics/en/stateless-invoices.md
=> Newsletters: add 236 (2023-02-01)

_posts/en/newsletters/2023-02-08-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/offers.md
=> Newsletters: add 237 (2023-02-08)

_posts/en/newsletters/2023-02-15-newsletter.md
Addresses @jirijakes comment here: https://github.com/bitcoinops/bitcoinops.github.io/pull/1010#discussion_r1106979736
=> News238: Tapscript signature malleability fixup

_posts/en/newsletters/2023-02-15-newsletter.md
Reported by @ajtowns https://github.com/bitcoinops/bitcoinops.github.io/pull/1010#pullrequestreview-1301637599
=> News238: correction, s/pull request/issue/

_posts/cs/newsletters/2023-02-15-newsletter.md, _posts/ja/newsletters/2023-02-15-newsletter.md
Apply #1015 to other languages.
=> Newsletter-238:Apply LDK 2002 fixup to translations

_posts/en/newsletters/2023-02-22-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/dual-funding.md, _topics/en/miniscript.md, _topics/en/multipath-payments.md, _topics/en/offers.md, _topics/en/output-script-descriptors.md, _topics/en/replace-by-fee.md, _topics/en/splicing.md, _topics/en/vaults.md
=> Newsletters: add 239 (2023-02-22)

_posts/en/newsletters/2023-03-01-newsletter.md, _topics/en/hd-key-generation.md, _topics/en/offers.md
=> Newsletters: add 240 (2023-03-01)

_posts/en/newsletters/2023-03-15-newsletter.md, _topics/en/assumeutxo.md, _topics/en/utreexo.md
=> Newsletters: add 242 (2023-03-15)

_posts/en/newsletters/2023-03-08-newsletter.md, _posts/en/podcast/2023-03-09-newsletter-recap.md
Adds podcast for newsletter 241. The podcast audio is live on the RSS feed. Awaiting transcription.
=> Podcasts: Add 241 recap

_posts/en/newsletters/2023-03-22-newsletter.md
=> Newsletters: add 243 (2023-03-22)

_data/schemas/topics.yaml, _posts/en/newsletters/2023-04-05-newsletter.md, _topics/en/proof-of-payment.md, _topics/en/rendez-vous-routing.md, _topics/en/wallet-labels.md, _topics/en/watchtowers.md
(Sorry there were no Bitcoin Core PRs; if the alternative PRs are too alien to you, let me know and I'll write them up.)
=> Newsletters: add 245 (2023-04-05)

en/publications.md
=> Publications: typo

_posts/en/newsletters/2023-04-19-newsletter.md, _topics/en/splicing.md
=> Newsletters: add 247 (2023-04-19)

_posts/en/newsletters/2023-04-26-newsletter.md, _topics/en/cpfp.md, _topics/en/ephemeral-anchors.md, _topics/en/replace-by-fee.md, _topics/en/transaction-bloom-filtering.md, _topics/en/transaction-origin-privacy.md, _topics/en/transaction-pinning.md
=> Newsletters: add 248 (2023-04-26)

_posts/en/newsletters/2023-05-03-newsletter.md, _topics/en/adaptor-signatures.md, _topics/en/covenants.md, _topics/en/multisignature.md, _topics/en/op_checktemplateverify.md, _topics/en/psbt.md, _topics/en/vaults.md
=> Newsletters: add 249 (2023-05-03)

_includes/linkers/issues.md, _includes/references.md, _posts/en/newsletters/2023-05-10-newsletter.md
Not quite finished; will update Monday.
=> Newsletters: add 250 (2023-05-10)

_posts/cs/newsletters/2023-05-10-newsletter.md
=> Newsletter-250: Add Czech translation

_includes/specials/policy/en/01-why-mempool.md, _posts/en/newsletters/2023-05-17-newsletter.md, _topics/en/assumeutxo.md, _topics/en/channel-jamming-attacks.md, _topics/en/dual-funding.md, _topics/en/package-relay.md, _topics/en/payjoin.md, _topics/en/silent-payments.md, _topics/en/zero-conf-channels.md
=> Newsletters: add 251 (2023-05-17)

_includes/specials/policy/en/02-cache-utility.md, _posts/en/newsletters/2023-05-24-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/coin-selection.md, _topics/en/hd-key-generation.md, _topics/en/miniscript.md, _topics/en/musig.md, _topics/en/signet.md, _topics/en/utreexo.md, _topics/en/wallet-labels.md
=> Newsletters: add 252 (2023-05-24)

_posts/en/newsletters/2023-05-24-newsletter.md, _posts/en/podcast/2023-05-25-newsletter-recap.md
=> Podcast: add 252 recap

_includes/specials/policy/en/04-feerate-estimation.md, _posts/en/2023-05-17-policy.md, _posts/en/newsletters/2023-06-07-newsletter.md, _topics/en/joinpools.md, _topics/en/op_checksigfromstack.md, _topics/en/op_checktemplateverify.md
- Lede, releases/RCs, topic entries @harding 
- Feerate estimates @glozow 
- Bitcoin Core 26485 @glozow 
- LND 7645 @bitschmidty
=> Newsletters: add 254 (2023-06-07)

_topics/en/jit-channels.md, _topics/en/multipath-payments.md, _topics/en/onion-messages.md, _topics/en/payment-secrets.md, _topics/en/spontaneous-payments.md, _topics/en/submarine-swaps.md
I forgot to add these during the edit of the newsletter before publication, so add them now.
=> News256: add topic entries

_posts/fr/newsletters/2023-06-07-newsletter.md
correct wrong link : 
{% include specials/policy/fr/04-estimation-taux-de-frais.md %}
=> News-fr 254 : edit to correct wrong link 

Makefile, _posts/en/podcast/2023-02-09-newsletter-recap.md, _posts/en/podcast/2023-04-06-newsletter-recap.md, _posts/en/podcast/2023-04-13-newsletter-recap.md, _posts/en/podcast/2023-04-20-newsletter-recap.md, _posts/en/podcast/2023-04-27-newsletter-recap.md, _posts/en/podcast/2023-05-04-newsletter-recap.md, _posts/en/podcast/2023-05-11-newsletter-recap.md, _posts/en/podcast/2023-05-18-newsletter-recap.md, _posts/en/podcast/2023-06-01-newsletter-recap.md, _posts/en/podcast/2023-06-08-newsletter-recap.md, _posts/en/podcast/2023-06-15-newsletter-recap.md, _posts/en/podcast/2023-06-22-newsletter-recap.md, _posts/en/podcast/2023-06-29-newsletter-recap.md
Addresses https://github.com/bitcoinops/bitcoinops.github.io/pull/1161#discussion_r1240212915
Apparently some some people often say the same word twice in a row row.
=> [Tests] Suppress duplicate-words-test on podcast transcripts

README.md, docker.md
Deal with a range of system environment problems by docker and make it deploy easier
=> Deal with a range of system environment problems by docker and make it deploy easier

_includes/specials/policy/en/09-proposals.md, _posts/en/2023-05-17-policy.md, _posts/en/newsletters/2023-07-12-newsletter.md
=> Newsletters: add 259 (2023-07-12)

_includes/specials/policy/en/10-get-involved.md, _posts/en/2023-05-17-policy.md, _posts/en/newsletters/2023-07-19-newsletter.md, _posts/en/podcast/2023-07-13-newsletter-recap.md, _topics/en/anonymity-networks.md, _topics/en/discreet-log-contracts.md, _topics/en/payjoin.md, _topics/en/side-channels.md, _topics/en/splicing.md
=> Newsletters: add 260 (2023-07-19)

_posts/en/newsletters/2023-07-26-newsletter.md, _topics/en/channel-announcements.md, _topics/en/channel-jamming-attacks.md, _topics/en/cluster-mempool.md, _topics/en/ephemeral-anchors.md, _topics/en/musig.md, _topics/en/package-relay.md, _topics/en/redundant-overpayments.md, _topics/en/replace-by-fee.md, _topics/en/taproot.md, _topics/en/version-3-transaction-relay.md
=> Newsletters: add 261 (2023-07-26)

_posts/en/podcast/2023-07-20-newsletter-recap.md
Small end quote fixup for the transcription
=> Podcast: 260 transcription fixup

_posts/fr/newsletters/2020-12-23-newsletter.md, _posts/fr/newsletters/2021-12-22-newsletter.md, _posts/fr/newsletters/2022-09-07-newsletter.md, _posts/fr/newsletters/2022-09-14-newsletter.md, _posts/fr/newsletters/2022-09-21-newsletter.md, _posts/fr/newsletters/2022-09-28-newsletter.md, _posts/fr/newsletters/2022-10-05-newsletter.md, _posts/fr/newsletters/2022-10-12-newsletter.md, _posts/fr/newsletters/2022-10-19-newsletter.md, _posts/fr/newsletters/2022-10-26-newsletter.md, _posts/fr/newsletters/2022-11-02-newsletter.md, _posts/fr/newsletters/2022-11-09-newsletter.md, _posts/fr/newsletters/2022-11-16-newsletter.md, _posts/fr/newsletters/2022-11-23-newsletter.md, _posts/fr/newsletters/2022-11-30-newsletter.md, _posts/fr/newsletters/2022-12-07-newsletter.md, _posts/fr/newsletters/2022-12-14-newsletter.md, _posts/fr/newsletters/2022-12-21-newsletter.md, _posts/fr/newsletters/2023-01-04-newsletter.md, _posts/fr/newsletters/2023-01-11-newsletter.md, _posts/fr/newsletters/2023-02-01-newsletter.md, _posts/fr/newsletters/2023-02-08-newsletter.md, _posts/fr/newsletters/2023-02-15-newsletter.md, _posts/fr/newsletters/2023-02-22-newsletter.md, _posts/fr/newsletters/2023-03-01-newsletter.md, _posts/fr/newsletters/2023-03-08-newsletter.md, _posts/fr/newsletters/2023-03-15-newsletter.md, _posts/fr/newsletters/2023-03-22-newsletter.md, _posts/fr/newsletters/2023-05-17-newsletter.md
@Copinmalin: I got all the titles, except the yearly reviews aligned. What’s your favorite out of the following?
- Revue spéciale Année 2020'
- Spécial Bilan 2021'
- Spéciale Revue annuelle 2022'
--------------
Edit: all ready for review. Below is an overview of what changed
**Before**
> 2020-12-23-newsletter.md:title: 'Bulletin Bitcoin Optech #129: Revue spéciale Année 2020'
> 2021-12-22-newsletter.md:title: 'Bulletin Bitcoin Optech #180: Spécial Bilan 2021'
> 2022-09-07-newsletter.md:title: 'Bitcoin Optech Newsletter #216'
> 2022-09-14-newsletter.md:title: 'Bitcoin Optech Newsletter #217'
> 2022-09-21-newsletter.md:title: 'Bitcoin Optech Newsletter #218'
> 2022-09-28-newsletter.md:title: 'Bitcoin Optech Newsletter #219'
> 2022-10-05-newsletter.md:title: 'Bitcoin Optech Newsletter #220' …
=> Harmonize titles of French Newsletters

Makefile, _includes/templates/compatibility/rbf.md, _posts/en/newsletters/2023-08-09-newsletter.md, _topics/en/channel-jamming-attacks.md, _topics/en/codex32.md, _topics/en/htlc-endorsement.md, _topics/en/onion-messages.md, _topics/en/replace-by-fee.md, _topics/en/responsible-disclosures.md, _topics/en/silent-payments.md, _topics/en/splicing.md
=> Newsletters: add 263 (2023-08-09)

_posts/en/newsletters/2023-08-23-newsletter.md, _topics/en/generic-signmessage.md, _topics/en/op_checksigfromstack.md, _topics/en/peer-storage.md, _topics/en/threshold-signature.md, _topics/en/uneconomical-outputs.md, _topics/en/utreexo.md
=> Newsletters: add 265 (2023-08-23)

_topics/en/musig.md
Closes https://github.com/bitcoinops/bitcoinops.github.io/issues/1270
=> Topics: musig field report mention

_posts/en/newsletters/2023-09-06-newsletter.md, _topics/en/threshold-signature.md
(Sorry the PR is being opened late.)
=> Newsletters: add 267 (2023-09-06)

_posts/en/newsletters/2023-09-20-newsletter.md, _topics/en/coin-selection.md, _topics/en/offers.md, _topics/en/rendez-vous-routing.md, _topics/en/v2-p2p-transport.md
Note: I would have liked to have covered John Law's LN with covenants proposal from last week in this newsletter, but I'm wrapping up some travel with family and ran out of time to give it a proper treatment.  I'll give it the attention it deserves in next week's newsletter.
=> Newsletters: add 269 (2023-09-20)

_posts/en/newsletters/2023-10-04-newsletter.md, _topics/en/compact-block-filters.md, _topics/en/multipath-payments.md, _topics/en/payment-probes.md, _topics/en/taproot.md, _topics/en/unannounced-channels.md
=> Newsletters: add 271 (2023-10-04)

_posts/en/newsletters/2023-10-18-newsletter.md
=> Newsletters: add 273 (2023-10-18)

_posts/zh/newsletters/2023-10-18-newsletter.md
* newsletter273zh
* Apply suggestions from code review
* fix style
---------
=> Newsletter-273: add Chinese translation

_posts/fr/newsletters/2023-06-28-newsletter.md, _posts/fr/newsletters/2023-07-05-newsletter.md, _posts/fr/newsletters/2023-07-12-newsletter.md, _posts/fr/newsletters/2023-07-19-newsletter.md, _posts/fr/newsletters/2023-07-26-newsletter.md, _posts/fr/newsletters/2023-08-02-newsletter.md, _posts/fr/newsletters/2023-09-27-newsletter.md, _posts/fr/newsletters/2023-10-18-newsletter.md, _posts/fr/newsletters/2023-11-01-newsletter.md, _posts/fr/newsletters/2023-11-08-newsletter.md
@Copinmalin can you take a look?
It looks like the timestamps for the podcast were copied over during the translation and I missed it in review.
=> French translation fixups

_posts/ja/2023-11-15-wizardsardine-miniscript.md
=> JA: add miniscript blog post

_posts/en/newsletters/2023-11-29-newsletter.md, _topics/en/liquidity-advertisements.md
=> Newsletters: add 279 (2023-11-29)

_posts/en/newsletters/2023-12-20-newsletter.md
=> Newsletters: add 282 (2023 year in review)

_posts/cs/newsletters/2023-03-29-newsletter.md, _posts/en/newsletters/2018-12-28-newsletter.md, _posts/en/newsletters/2019-02-19-newsletter.md, _posts/en/newsletters/2019-05-29-newsletter.md, _posts/en/newsletters/2023-03-29-newsletter.md, _posts/fr/newsletters/2023-03-29-newsletter.md, _posts/ja/newsletters/2023-03-29-newsletter.md, _posts/zh/newsletters/2023-03-29-newsletter.md, _topics/en/channel-factories.md
Looks like the URL changed at some point.
=> Fix link to Channel Factories paper

_posts/en/newsletters/2024-01-17-newsletter.md
=> News285: fix typo

_includes/references.md, _posts/en/newsletters/2024-01-24-newsletter.md, _topics/en/cluster-mempool.md, _topics/en/ephemeral-anchors.md, _topics/en/rendez-vous-routing.md, _topics/en/responsible-disclosures.md, _topics/en/statechains.md, _topics/en/trampoline-payments.md, _topics/en/trimmed-htlc.md, _topics/en/version-3-transaction-relay.md
- Lede, releases/RCs, topic entries @harding 
- PR summaries @harding 
- Client/Services @bitschmidty
=> Newsletters: add 286 (2024-01-24)

_includes/linkers/issues.md, _posts/en/newsletters/2024-01-31-newsletter.md, _topics/en/cluster-mempool.md, _topics/en/cpfp-carve-out.md, _topics/en/fee-sourcing.md, _topics/en/op_checktemplateverify.md, _topics/en/rendez-vous-routing.md, _topics/en/replace-by-fee.md, _topics/en/simple-taproot-channels.md, _topics/en/trampoline-payments.md, _topics/en/version-3-transaction-relay.md, _topics/en/watchtowers.md
=> Newsletters: add 287 (2024-01-31)

_posts/en/newsletters/2024-02-07-newsletter.md, _topics/en/cluster-mempool.md, _topics/en/compact-block-relay.md, _topics/en/dual-funding.md, _topics/en/replace-by-fee.md, _topics/en/responsible-disclosures.md, _topics/en/splicing.md, _topics/en/taproot.md, _topics/en/transaction-pinning.md, _topics/en/v2-p2p-transport.md, _topics/en/version-3-transaction-relay.md, _topics/en/zero-conf-channels.md
=> Newsletters: add 288 (2024-02-07)

_posts/en/newsletters/2024-02-14-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/cluster-mempool.md, _topics/en/hd-key-generation.md, _topics/en/version-3-transaction-relay.md
=> Newsletters: add 289 (2024-02-14)

_posts/cs/newsletters/2024-01-24-newsletter.md, _posts/cs/newsletters/2024-01-31-newsletter.md, _posts/cs/newsletters/2024-02-14-newsletter.md
Please, merge after #1512, thank you!
During translating 289 I came up with more accurate translation of "imbued v3 logic", therefore fixing past occurrences in the same PR.
=> Newsletter-289: Translate into Czech

_posts/en/newsletters/2024-02-21-newsletter.md, _topics/en/coin-selection.md, _topics/en/dual-funding.md, _topics/en/eclipse-attacks.md, _topics/en/offers.md, _topics/en/payjoin.md, _topics/en/replace-by-fee.md, _topics/en/responsible-disclosures.md, _topics/en/silent-payments.md
(I haven't proofread my own writing yet, sorry if there's excessive errors.)
=> Newsletters: add 290 (2024-02-21)

_posts/en/newsletters/2024-02-28-newsletter.md, _topics/en/acc.md, _topics/en/coin-selection.md, _topics/en/dual-funding.md, _topics/en/ecash.md, _topics/en/op_cat.md, _topics/en/vaults.md, _topics/en/watchtowers.md
=> Newsletters: add 291 (2024-02-28)

_includes/references.md, _posts/en/newsletters/2024-03-06-newsletter.md, _topics/en/coin-selection.md, _topics/en/dual-funding.md, _topics/en/musig.md, _topics/en/vaults.md
=> Newsletters: add 292 (2024-03-06)

_posts/en/newsletters/2024-03-13-newsletter.md, _topics/en/op_cat.md, _topics/en/payment-probes.md, _topics/en/simple-taproot-channels.md, _topics/en/soft-fork-activation.md
=> Newsletters: add 293 (2024-03-13)

_posts/en/newsletters/2024-03-27-newsletter.md, _topics/en/dual-funding.md, _topics/en/fee-estimation.md, _topics/en/fee-sourcing.md, _topics/en/fee-sponsorship.md, _topics/en/free-relay.md, _topics/en/psbt.md, _topics/en/schnorr-signatures.md, _topics/en/spontaneous-payments.md, _topics/en/trampoline-payments.md
=> Newsletters: add 295 (2024-03-27)

_posts/en/newsletters/2024-03-27-newsletter.md
I should have caught this in review 🙋
=> News295: feefilter bip link fixup

_posts/en/newsletters/2024-04-03-newsletter.md, _topics/en/accidental-confiscation.md, _topics/en/cluster-mempool.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/duplicate-transactions.md, _topics/en/gap-limits.md, _topics/en/package-relay.md, _topics/en/replace-by-fee.md, _topics/en/time-warp.md, _topics/en/version-3-transaction-relay.md
Sorry this is late and incomplete, I came down with a cold.  I'll keep working on it as I have energy.
=> Newsletters: add 296 (2024-04-03)

_topics/en/duplicate-transactions.md, _topics/en/time-warp.md
I believe this addresses all comments from #1586 (to date), thanks @bitschmidty and @murchandamus !
=> Topics: edits to dup txes and time warp

_posts/en/newsletters/2024-04-17-newsletter.md, _topics/en/cluster-mempool.md, _topics/en/replace-by-fee.md
~~I'll check later in the week/weekend to look again for possible news stories or PR merges, but I'm guessing a lot of people are busy with the conference, so it might be a slow news week.~~
=> Newsletters: add 298 (2024-04-17)

_posts/en/newsletters/2024-04-24-newsletter.md, _topics/en/compact-block-relay.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/eclipse-attacks.md, _topics/en/fee-estimation.md, _topics/en/replace-by-fee.md, _topics/en/time-warp.md, _topics/en/transaction-pinning.md
I'll check again for any notable merges Friday.
=> Newsletters: add 299 (2024-04-24)

_layouts/topic.html
This fixes a missed variable name update from #1628
=> Topics layout: correct variable name

_posts/en/newsletters/2024-05-01-newsletter.md, _topics/en/assumeutxo.md, _topics/en/coin-selection.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/cross-input-signature-aggregation.md, _topics/en/op_checktemplateverify.md, _topics/en/output-script-descriptors.md, _topics/en/package-relay.md, _topics/en/signet.md, _topics/en/silent-payments.md
=> Newsletters: add 300 (2024-05-01)

_posts/en/newsletters/2021-03-24-newsletter.md, _posts/en/newsletters/2024-05-08-newsletter.md, _topics/en/op_checksigfromstack.md, _topics/en/package-relay.md, _topics/en/quantum-resistance.md
Sorry this is late.  I got nerd snipped by the lamport discussion.  ~~I'll take this out of draft when the main content is ready for review.~~  Ready for review now; sorry for the delay!
=> Newsletters: add 301 (2024-05-08)

_posts/en/newsletters/2024-05-08-newsletter.md
Reported by @darosior: https://github.com/bitcoinops/bitcoinops.github.io/pull/1645/files/e5875a622cf59a86b389c78a2c6959fcf62438af#r1593946375
I'll merge as soon as tests pass.
=> News301 correction: OP_CHECKSIG -> OP_CHECKSIGVERIFY

_topics/en/silent-payments.md
Provide more background information on silent payments, since the topic page was largely a stub.
First time contributing and I mostly pulled things from the [proposal](https://gist.github.com/RubenSomsen/c43b79517e7cb701ebf77eec6dbb46b8)
=> Update silent payments topic

_posts/en/newsletters/2024-05-15-newsletter.md, _topics/en/op_cat.md, _topics/en/op_checktemplateverify.md, _topics/en/output-script-descriptors.md, _topics/en/utreexo.md
=> Newsletters: add 302 (2024-05-15)

_posts/zh/newsletters/2018-07-31-newsletter.md, _posts/zh/newsletters/2018-10-30-newsletter.md, _posts/zh/newsletters/2018-11-13-newsletter.md
Actions:
1. Updated the link comment in issue #6, changing "C-lightning" to "Core Lightning" instead of "c-lightning."
2. Fixed a link error in issue #19 that affected issue #21, and modified the workflow to avoid such situations in the future.
3. Added the translation for issue #21.
=> Newsletter-21: translate into Chinese

_posts/en/newsletters/2024-05-15-newsletter.md
Reported by @ajtowns (thanks!)
=> News302: typo fix for multi_a

_topics/en/pooled-mining.md
Adds a topic page for some of the suggested topics from #721
=> Topics: add pooled mining

_posts/en/newsletters/2024-05-24-newsletter.md, _topics/en/channel-commitment-upgrades.md, _topics/en/ecash.md, _topics/en/miniscript.md, _topics/en/onion-messages.md, _topics/en/op_cat.md, _topics/en/package-relay.md, _topics/en/psbt.md, _topics/en/silent-payments.md, _topics/en/simple-taproot-channels.md
Aiming to be ready for another Friday publication.
=> Newsletters: add 304 (2024-05-24)

_posts/en/newsletters/2024-05-31-newsletter.md
Note: appologies, this draft might be a bit rough; I was a bit rushed for time and my preview setup broke.
=> Newsletters: add 305 (2024-05-31)

_posts/en/newsletters/2024-06-07-newsletter.md
CC @darosior 
I'll merge after tests pass.
=> News306: amend security disclosure section to recommend point releases

_posts/en/newsletters/2024-06-07-newsletter.md
Addresses issues mentioned in https://github.com/bitcoinops/bitcoinops.github.io/pull/1714#discussion_r1630230324 by @murchandamus
=> News306: edits to testnet section

_posts/en/newsletters/2024-06-14-newsletter.md, _topics/en/cltv-expiry-delta.md, _topics/en/onion-messages.md, _topics/en/quantum-resistance.md, _topics/en/rendez-vous-routing.md, _topics/en/version-3-transaction-relay.md
=> Newsletters: add 307 (2024-06-14)

_posts/en/newsletters/2024-06-14-newsletter.md
Bad miss by me on reviewing this newsletter, my apologies
=> News307: review club fixup

_posts/en/newsletters/2024-05-24-newsletter.md, _posts/en/newsletters/2024-06-21-newsletter.md, _topics/en/fee-estimation.md, _topics/en/offers.md, _topics/en/payment-probes.md, _topics/en/psbt.md, _topics/en/rendez-vous-routing.md, _topics/en/responsible-disclosures.md, _topics/en/silent-payments.md
=> Newsletters: add 308 (2024-06-21)

_includes/functions/get-mention-date.md, _posts/en/newsletters/2024-07-05-newsletter.md, _topics/en/async-payments.md, _topics/en/cve.md, _topics/en/hd-key-generation.md, _topics/en/miniscript.md, _topics/en/musig.md, _topics/en/offers.md, _topics/en/output-script-descriptors.md, _topics/en/pooled-mining.md, _topics/en/psbt.md, _topics/en/rendez-vous-routing.md, _topics/en/responsible-disclosures.md
=> Newsletters: add 310 (2024-07-05)

_posts/en/newsletters/2024-07-12-newsletter.md, _topics/en/testnet.md
Shaping up to be a short one this week!
=> Newsletters: add 311 (2024-07-12)

_posts/en/newsletters/2024-06-07-newsletter.md
Small correction via https://github.com/bitcoinops/bitcoinops.github.io/issues/1738
=> News306: Rust Bitcoin 2644 fixup

_posts/ja/newsletters/2024-06-07-newsletter.md
=> Newsletter-306-ja:Rust Bitcoin 264 fixup

_posts/en/podcast/2024-04-11-newsletter-recap.md
🙋 my bad on missing publishing this previously
=> Podcast: add 297 transcription

_posts/en/newsletters/2024-07-19-newsletter.md, _topics/en/cluster-mempool.md, _topics/en/jit-channels.md, _topics/en/onion-messages.md, _topics/en/pooled-mining.md, _topics/en/threshold-signature.md, _topics/en/timelocks.md
=> Newsletters: add 312 (2024-07-19)

_posts/en/newsletters/2024-07-19-newsletter.md, _posts/en/newsletters/2024-07-26-newsletter.md, _topics/en/assumeutxo.md, _topics/en/cluster-mempool.md, _topics/en/free-relay.md, _topics/en/offers.md, _topics/en/replace-by-fee.md, _topics/en/responsible-disclosures.md, _topics/en/time-warp.md, _topics/en/version-3-transaction-relay.md
=> Newsletters: add 313 (2024-07-26)

_posts/en/newsletters/2024-07-19-newsletter.md
follow-on to PR #1788 (newsletter 312, 2024-07-19)
=> small grammar fixups to NL312 Rust Bitcoin

_includes/references.md, _posts/en/newsletters/2024-08-02-newsletter.md, _topics/en/cluster-mempool.md, _topics/en/erlay.md, _topics/en/fee-estimation.md, _topics/en/offers.md, _topics/en/responsible-disclosures.md
=> Newsletters: add 314 (2024-08-02)

_posts/en/newsletters/2024-08-02-newsletter.md, _posts/en/podcast/2024-08-06-newsletter-recap.md
also fixes up a new314 news title
=> Podcast: add 314 recap

_posts/en/newsletters/2024-08-23-newsletter.md, _topics/en/assumeutxo.md, _topics/en/client-side-validation.md, _topics/en/exfiltration-resistant-signing.md, _topics/en/pay-to-contract-outputs.md, _topics/en/pooled-mining.md, _topics/en/rendez-vous-routing.md, _topics/en/testnet.md
=> Newsletters: add 317 (2024-08-23)

_topics/en/ephemeral-anchors.md, _topics/en/version-3-transaction-relay.md
Add implementation links for each in the "Primary code and documentation" topic section.
=> topics: update v3 transaction relay and ephemeral anchors

_posts/en/newsletters/2024-08-30-newsletter.md, en/internal/sources.md
=> Newsletters: add 318 (2024-08-30)

_posts/en/newsletters/2024-09-06-newsletter.md
=> Newsletters: add 319 (2024-09-06)

_posts/en/newsletters/2024-09-13-newsletter.md
=> Newsletters: add 320 (2024-09-13)

_posts/cs/newsletters/2024-09-13-newsletter.md, _posts/en/newsletters/2024-09-13-newsletter.md, _posts/ja/newsletters/2024-09-13-newsletter.md
=> News320: pr review fixup

_topics/en/channel-announcements.md
Addressed feedback from #1822 .  Will merge after tests pass to enhance this topic for the upcoming newsletter.  I'll be happy to address additional feedback after.
=> Topics: channel announcements: updates for v1/1.5/2 gossip

_posts/en/newsletters/2024-09-27-newsletter.md, _topics/en/acc.md, _topics/en/channel-announcements.md, _topics/en/channel-jamming-attacks.md, _topics/en/client-side-validation.md, _topics/en/htlc-endorsement.md, _topics/en/responsible-disclosures.md
=> Newsletters: add 322 (2024-09-27)

_includes/references.md, _posts/en/newsletters/2024-10-04-newsletter.md, _topics/en/dual-funding.md, _topics/en/liquidity-advertisements.md, _topics/en/offers.md, _topics/en/pooled-mining.md, _topics/en/splicing.md
=> Newsletters: add 323 (2024-10-04)

_posts/en/newsletters/2024-10-11-newsletter.md, _topics/en/client-side-validation.md, _topics/en/compact-block-relay.md, _topics/en/ephemeral-anchors.md, _topics/en/kindred-replace-by-fee.md, _topics/en/package-relay.md, _topics/en/responsible-disclosures.md, _topics/en/testnet.md, _topics/en/version-3-transaction-relay.md
=> Newsletters: add 324 (2024-10-11)

_posts/ja/newsletters/2024-10-11-newsletter.md
After PR #1946 is merged the tests will pass.
=> Newsletter-324:Translate into Japanese

_topics/en/musig.md
to follow up on https://github.com/bitcoinops/bitcoinops.github.io/pull/1942#discussion_r1797642476
=> topics: add MuSig2 implementations and newsletter 324 mention

_posts/en/2024-10-10-wallet-integration-guide.md
=> Fix typo in wallet integration guide

_posts/en/newsletters/2024-10-18-newsletter.md, _topics/en/adaptor-signatures.md, _topics/en/ark.md, _topics/en/channel-announcements.md, _topics/en/ephemeral-anchors.md, _topics/en/pooled-mining.md, _topics/en/ptlc.md, _topics/en/version-3-transaction-relay.md
=> Newsletters: add 325 (2024-10-18)

_posts/cs/newsletters/2024-10-18-newsletter.md
Please, merge #1949 (previous newsletter) first :pray:
=> Newsletter-325: Translate into Czech

_posts/en/newsletters/2024-11-01-newsletter.md, _topics/en/channel-announcements.md, _topics/en/channel-factories.md, _topics/en/discrete-log-equivalency.md, _topics/en/duplex-micropayment-channels.md, _topics/en/silent-payments.md
=> Newsletters: add 327 (2024-11-01)

_posts/en/newsletters/2024-11-08-newsletter.md, _topics/en/ephemeral-anchors.md, _topics/en/uneconomical-outputs.md
=> Newsletters: add 328 (2024-11-08)

_posts/en/newsletters/2024-11-15-newsletter.md, _topics/en/channel-factories.md, _topics/en/ln-penalty.md, _topics/en/replace-by-fee.md, _topics/en/timeout-trees.md
=> Newsletters: add 329 (2024-11-15)

_posts/en/newsletters/2024-11-08-newsletter.md, _posts/en/podcast/2024-11-05-newsletter-recap.md, _posts/en/podcast/2024-11-12-newsletter-recap.md
also includes a [327 metadata fixup](https://github.com/bitcoinops/bitcoinops.github.io/commit/741a2be6598b73f638a0123de4d1a14643004a39)
=> Podcast: add 328 recap

_topics/en/timeout-trees.md
Thanks to @johnlaw2 for both the invention and pointing me to his original description of it.
=> Topics: timeout trees: cite original idea

_posts/en/newsletters/2024-11-29-newsletter.md, _topics/en/basic-bitcoin-lisp-language.md, _topics/en/cluster-mempool.md, _topics/en/dual-funding.md, _topics/en/simplicity.md, _topics/en/splicing.md
=> Newsletters: add 331 (2024-11-29)

_includes/references.md, _includes/snippets/recap-ad.md, _posts/en/newsletters/2024-11-29-newsletter.md, _posts/en/newsletters/2024-12-06-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/channel-commitment-upgrades.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/duplicate-transactions.md, _topics/en/htlc-endorsement.md, _topics/en/output-script-descriptors.md, _topics/en/splicing.md, _topics/en/time-warp.md, _topics/en/timelocks.md
=> Newsletters: add 332 (2024-12-06)

_posts/en/newsletters/2024-12-20-newsletter.md, _posts/en/podcast/2024-12-23-newsletter-recap.md
Includes a few more updates to the original (YiR) newsletter in terms of formatting to support the podcast linking (apologies I should have added these changes in my original newsletter review)
=> Podcast: add 334 recap

_includes/references.md, _includes/snippets/recap-ad.md, _posts/en/newsletters/2025-01-03-newsletter.md, en/internal/sources.md
~~Opening as draft as I haven't had time to spell check or self edit.  Please don't waste your time reviewing until this is out of draft.~~
=> Newsletters: add 335 (2025-01-03)

_includes/references.md, _posts/en/newsletters/2025-01-10-newsletter.md, _topics/en/acc.md, _topics/en/coinjoin.md, _topics/en/discrete-log-equivalency.md, _topics/en/eltoo.md, _topics/en/jit-channels.md, _topics/en/op_cat.md, _topics/en/op_checktemplateverify.md, _topics/en/payment-batching.md, _topics/en/peer-storage.md, _topics/en/quantum-resistance.md, _topics/en/replacement-cycling.md, _topics/en/threshold-signature.md, _topics/en/time-warp.md, _topics/en/timelocks.md, _topics/en/transaction-pinning.md, _topics/en/transitory-soft-forks.md, _topics/en/vaults.md
Note: we'd normally include a PR Review Club section but it looks like there's no meeting scheduled for this month.  If I'm missing something, @stickies-v please feel free to add the section.  You're also welcome to add it to any later newsletter this month.  I'll check in on the Club website again next month.
=> Newsletters: add 336 (2025-01-10)

_includes/references.md, _posts/en/newsletters/2025-01-17-newsletter.md, _topics/en/discreet-log-contracts.md, _topics/en/discrete-log-equivalency.md, _topics/en/ecash.md, _topics/en/payjoin.md, _topics/en/pooled-mining.md, _topics/en/psbt.md, _topics/en/silent-payments.md, _topics/en/splicing.md, _topics/en/v2-p2p-transport.md
=> Newsletters: add 337 (2025-01-17)

_posts/en/newsletters/2022-12-21-newsletter.md, _posts/en/podcast/2022-12-22-newsletter-recap.md
=> WIP Podcast: add 231 recap

_posts/en/newsletters/2025-01-24-newsletter.md, _topics/en/coinswap.md, _topics/en/discreet-log-contracts.md, _topics/en/joinpools.md, _topics/en/musig.md, _topics/en/output-script-descriptors.md, _topics/en/package-relay.md, _topics/en/payjoin.md, _topics/en/psbt.md, _topics/en/simple-taproot-channels.md
=> Newsletters: add 338 (2025-01-24)

_posts/en/newsletters/2025-01-31-newsletter.md, _topics/en/compact-block-relay.md, _topics/en/cross-input-signature-aggregation.md, _topics/en/liquidity-advertisements.md, _topics/en/musig.md, _topics/en/output-script-descriptors.md, _topics/en/peer-storage.md, _topics/en/replacement-cycling.md, _topics/en/responsible-disclosures.md, _topics/en/time-warp.md, _topics/en/x-only-public-keys.md
=> Newsletters: add 339 (2025-01-31)

_posts/de/newsletters/2025-02-07-newsletter.md, _posts/en/podcast/2025-01-28-newsletter-recap.md
- Complete German translation of newsletter #340
- formatting text
- Remove duplicate words and improve readability
=> German translation: Complete translation of newsletter #340

_posts/en/newsletters/2025-02-14-newsletter.md, _topics/en/probabilistic-payments.md
=> Newsletters: add 341 (2025-02-14)

_posts/de/newsletters/2025-02-07-newsletter.md, _posts/de/newsletters/2025-02-14-newsletter.md
This pull request adds the German translation for Bitcoin Optech Newsletter #341.
=> Add German translation for Newsletter #341

_posts/en/newsletters/2025-02-28-newsletter.md, _topics/en/rendez-vous-routing.md, _topics/en/x-only-public-keys.md
My apologies for opening the PR late.  We recently moved; it's just a few miles away from our old place but right now my life is in disarray.
=> Newsletters: add 343 (2025-02-28)

_posts/en/newsletters/2025-03-14-newsletter.md, _topics/en/anchor-outputs.md, _topics/en/erlay.md, _topics/en/probabilistic-payments.md, _topics/en/splicing.md
=> Newsletters: add 345 (2025-03-14)

_posts/en/newsletters/2025-04-04-newsletter.md, _topics/en/async-payments.md, _topics/en/quantum-resistance.md
Sorry this PR is being opened in draft.  At the time of opening, with lots of content still missing, it's our third-longest regular newsletter ever.  By the time it's done, it'll almost certainly be longer than any other regular newsletter and also longer than several of our year-end newsletters.
=> Newsletters: add 348 (2025-04-04)

_topics/en/vaults.md
Update broken link in vaults topic [issues #2258](https://github.com/bitcoinops/bitcoinops.github.io/issues/2258)
=> Update Möser-Eyal-Sirer vault proposal link in _topics/en/vaults.md

_posts/en/newsletters/2025-04-11-newsletter.md, _topics/en/acc.md, _topics/en/ark.md, _topics/en/assumeutxo.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/discreet-log-contracts.md, _topics/en/eltoo.md, _topics/en/fee-estimation.md, _topics/en/matt.md, _topics/en/op_checksigfromstack.md, _topics/en/op_checktemplateverify.md, _topics/en/package-relay.md, _topics/en/quantum-resistance.md, _topics/en/simple-taproot-channels.md, _topics/en/testnet.md, _topics/en/timelocks.md, _topics/en/trampoline-payments.md, _topics/en/utreexo.md
=> Newsletters: add 349 (2025-04-11)

_includes/references.md, _posts/en/newsletters/2025-04-18-newsletter.md, _topics/en/generic-signmessage.md, _topics/en/payment-secrets.md
If there's any simple news stories, I may add them today/tomorrow.  Otherwise, it'll be a short newsletter!
=> Newsletters: add 350 (2025-04-18)

_posts/ja/newsletters/2025-04-18-newsletter.md, ja/internal/sources.md
=> Newsletter-350:Translate into Japanese

_posts/fr/newsletters/2025-04-11-newsletter.md, notes.md
Some minor fixes for the french.
=> Update newsletter 349 translate in french

_posts/en/newsletters/2025-04-25-newsletter.md, _topics/en/cross-input-signature-aggregation.md, _topics/en/output-script-descriptors.md
=> Newsletters: add 351 (2025-04-25)

_includes/references.md, _posts/en/newsletters/2025-05-02-newsletter.md, _topics/en/cluster-mempool.md
No _changing consensus_ section this week as I have a awful cold and some other constraints on my time.  I'll either add it to another newsletter this month or save it up from an extra long section in June.
=> Newsletters: add 352 (2025-05-02)

_includes/references.md, _posts/en/newsletters/2025-05-09-newsletter.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/duplicate-transactions.md, _topics/en/hd-key-generation.md, _topics/en/output-linking.md, _topics/en/responsible-disclosures.md
=> Newsletters: add 353 (2025-05-09)

_includes/references.md, _posts/en/newsletters/2025-05-16-newsletter.md, _topics/en/acc.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/covenants.md, _topics/en/matt.md, _topics/en/op_checksigfromstack.md, _topics/en/op_checktemplateverify.md
=> Newsletters: add 354 (2025-05-16)

_posts/en/newsletters/2025-05-23-newsletter.md, _topics/en/payjoin.md, _topics/en/peer-storage.md, _topics/en/splicing.md
=> Newsletters: add 355 (2025-05-23)

STYLE-PT.md
I created this based on the German one, hoping it helps make Portuguese translations of the newsletter a bit easier.
=> feat: adds initial Portuguese style guide

_posts/de/newsletters/2025-01-31-newsletter.md, _posts/de/newsletters/2025-05-30-newsletter.md
=> Update internal links and anchors to point to German translations in 356 & 339

_posts/en/newsletters/2025-06-27-newsletter.md, _topics/en/anonymity-networks.md, _topics/en/attributable-failures.md, _topics/en/trampoline-payments.md
=> Newsletters: add 360 (2025-06-27)

_includes/snippets/recap-ad.md, _posts/ja/newsletters/2025-07-04-newsletter.md
I also fixed the issue where the recap release date was still on Thursday.
=> Newsletter-361:Translate into Japanese

_posts/en/newsletters/2025-07-18-newsletter.md
=> News363: client service fixup

_posts/en/newsletters/2025-07-25-newsletter.md, _topics/en/attributable-failures.md, _topics/en/consensus-cleanup-soft-fork.md, _topics/en/hd-key-generation.md, _topics/en/package-relay.md, _topics/en/quantum-resistance.md, _topics/en/responsible-disclosures.md
=> Newsletters: add 364 (2025-07-25)

_posts/en/newsletters/2025-08-01-newsletter.md, _topics/en/annex.md, _topics/en/compact-block-relay.md, _topics/en/fee-estimation.md, _topics/en/op_checktemplateverify.md, _topics/en/quantum-resistance.md, _topics/en/taproot.md, _topics/en/timelocks.md
=> Newsletters: add 365 (2025-08-01)

_topics/en/client-side-validation.md
Closes https://github.com/bitcoinops/bitcoinops.github.io/issues/2444
=> Topic: CSV RGB link updates

_posts/en/newsletters/2025-08-22-newsletter.md, _posts/ja/newsletters/2025-08-22-newsletter.md
and minor fix for the release of LND in english version.
=> Newsletter-368:Translate into Japanese

_posts/en/newsletters/2025-07-04-newsletter.md, _posts/en/newsletters/2025-08-29-newsletter.md, _posts/fr/newsletters/2025-07-04-newsletter.md, _topics/en/acc.md, _topics/en/splicing.md
=> Newsletters: add 369 (2025-08-29)

_posts/en/newsletters/2025-09-26-newsletter.md
=> Newsletters: add 373 (2025-09-26)
